### ISSUE TITLE
Get initial metadata profile from DAMP group

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#1]
Occasionally ping, watch, or otherwise interface with the folks in the DAMP working group in order to get the initial metadata fields used for the IDC effort.

Includes:
- [ ] Set of metadata fields
- [ ] Understanding which fields correspond to taxonomies or otherwise controlled vocabularies

**Comment by bseeger** [comment]
Here's a spreadsheet I started based on the library's minimum set of metadata fields required. I took that data and created a little drupal information about it, keeping in mind that it's a minimum set and will probably grow. 

https://docs.google.com/spreadsheets/d/13FIO83xGTEZs9XZnBofbM2Z2MiD5C83-j9SKDtlZrQI/edit#gid=0

**Comment by htpvu** [comment]
Done. DAMP report is here https://drive.google.com/open?id=1wfRNKDdM9UBRhij7O8bFJMGMLLnokaVK
