### ISSUE TITLE
Decide if Fedora, Triplestore are needed

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#10]
Since there are no current use cases for preservation or archiving, it may not be necessary to deploy Fedora as part of the stack right now (indeed, it might be advantageous to wait until fcrepo6).  Ping Sayeed about this for input.

**Comment by htpvu** [comment]
Elliot has written a doc laying the consideration regarding FEdora. https://docs.google.com/document/d/1c1J3GC3XLvUOv36jqB3Vo8xRcuoAvJCVS3WnJqJFAH4/edit#heading=h.cq20614a1981

**Comment by emetsger** [comment]
Completed.
