### ISSUE TITLE
Implement Header / Footer elements

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#101]
Acceptance criteria:
- [x] A user can enter a search in the global search widget in the header menu (iDC-7)
- [x] The header and footer are responsive to viewport widths
- [x] A user can visit other library sites from the top nav
- [x] A user can login to the admin portal from the top nav
- [x] A user can visit all the links in the header and footer 
- [x] A user can visit the contact us page
- [ ] If not on the home page there is a bread crumb navigational bar in the header (iDC-13)

Implement the header and footer for the pages as an independent task since they appear across all the pages and can be built separately from the rest of the pages.

The search input results page does not need to be fully functional for this task, but the search input should appear in location and styled per the designs, and have minimum functionality.

**Comment by jabrah** [comment]
These will likely include several menus. There is a way to "export" menus and custom blocks through the Drupal admin UI so they can be later migrated or imported. I haven't been able to get this feature working in my local Drupal env (not the full Islandora), so I'll have to check out how this is done and how to include the exported menus/blocks in the theme.

Most of the above tasks should be fairly easily doable if we ignore the exportable config described here. Maybe two days (2d) if we temporarily go with Drupal's built-in search widget. We can then address the global search while developing the full search components later. We'll need some extra time to figure out the config export and incorporate the exported config in the theme, maybe 1 - 2 days. This extra work will aid in other parts of development.
- [ ] templating and css work (2d)

**Comment by jabrah** [comment]
'm not sure if this is limited to custom modules, or if we can do this in the theme, but here's how to define menus in YML config files: https://www.drupal.org/docs/drupal-apis/menu-api/providing-module-defined-menu-links

**Comment by jaredgalanis** [comment]
![Screen Shot 2020-11-20 at 1 41 04 PM](https://user-images.githubusercontent.com/6305935/99837878-3e658100-2b36-11eb-85e4-b85f04393866.png)
