### ISSUE TITLE
Implement site’s Home page

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#102]
Design: [https://www.sketch.com/s/cc9f0d30-cccd-454f-a1f3-e00ec93bb85d](https://www.sketch.com/s/cc9f0d30-cccd-454f-a1f3-e00ec93bb85d)

Acceptance criteria:
- [x] A user can visit the home page route
- [ ] A user can interact with the contact us button and other available buttons (these may experience some shift11)

The home page should be developed in a way that allows a Drupal admin to alter content where possible. The main description appearing the center-left of the page is an example.

**Comment by jabrah** [comment]
IMO it won't be worth using the Tailwind CSS Drupal theme as it is as minimal of a base theme as possible, providing Tailwind assets and nothing else. It will be better for us to chose a more complete base theme and include Tailwind ourselves

- [ ] templating and css (2d)

**Comment by jaredgalanis** [comment]
I agree with @jabrah's analysis on the Tailwind module so we'll likely just install Tailwind ourselves

**Comment by jabrah** [comment]
Waiting on images now. I think Jared has one of the images, but for the design picked some random image as a placeholder. So I'll at least need the "official" image for the "Library Collections" card

**Comment by jaredgalanis** [comment]
![Screen Shot 2020-11-20 at 1 41 04 PM](https://user-images.githubusercontent.com/6305935/99837800-25f56680-2b36-11eb-8c2e-3bce8bdad145.png)
