### ISSUE TITLE
Implement Contact page / form

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#103]
Design: [https://www.sketch.com/s/631c2a98-9cc0-4f1c-8fb1-34ec5a364b7a](https://www.sketch.com/s/631c2a98-9cc0-4f1c-8fb1-34ec5a364b7a)

Use case: [https://docs.google.com/document/d/16JCMBTGlr1NQwh9tAxz28aAPxMyKuUHNBW-h2H9yjOc/edit#heading=h.irdrgv2a9uu4](https://docs.google.com/document/d/16JCMBTGlr1NQwh9tAxz28aAPxMyKuUHNBW-h2H9yjOc/edit#heading=h.irdrgv2a9uu4)

Acceptance criteria:

- [x] A user can visit the contact us page and fill out and submit the form (accessed from the button on the home page or the nav bar)
- [x] Form data are captured and sent to a configurable email address
- [ ] There is a requirement for captcha, so we’ll need to integrate with a captcha library
- [x] The form can be sent to the user submitting the form to their email or they can opt-out, via a checkbox
- [x] There exists some visual cue/indication that the message has been sent.

This contact us page contains a general version of the form that is otherwise accessed from the collection and item level pages. As such, this form does not require details about a specific collection or item, and it does not require a redirect upon form submission.

An example implementation of a form to email in Drupal: https://www.drupal.org/node/197122

**Comment by jabrah** [comment]
Check https://www.drupal.org/docs/8/core/modules/contact/overview as well

I don't think the copy sending is supported out of the box. May need to investigate another solution to support that :(

**Comment by jaredgalanis** [comment]
- [x] implement templating and css (2d)
- [ ] collect form data and handle accordingly (5d)
- [ ] testing (3d)

**Comment by jabrah** [comment]
Seems like the out-of-the-box feature of sending yourself a copy of the email only works for logged in users. Anonymous users aren't given the option

**Comment by jabrah** [comment]
```
The form can be sent to the user submitting the form to their email or they can opt-out, via a checkbox
```

@htpvu FYI, using the default contact module in Drupal, there will never be the checkbox to send a copy of the message to the input email, as it could be abused to send messages to arbitrary email addresses.
