### ISSUE TITLE
Implement Featured collections block on collection list page/items on collection detail page

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#104]
Acceptance criteria:
- [ ] Several collections are displayed in a content block area
- [ ] If there are more than three featured collections there is a paginated carousel that is navigable forward and back via controls
- [ ] The entire featured collection/item image and title / description is clickable and clicking takes a user to the collection/item detail view
    - [ ] **For Collections**, metadata fields used: title, truncated snippet of description (roughly 2 sentences) in ENGLISH.
    - [ ] **For items**, metadata fields used: Author/Creator, Date Created, Date Published

This task should first be explored as a generalizable feature that can be applied to both collection list and item list views. If there are difficulties with generalizing the feature then individualized featured blocks can be developed.

There likely will need to be a flag on collections that allow for a collection to be marked as featured for display in this part of the UI. There will also need to be a flag on an item that marks it as the preview image to be displayed for the collection. If there is no image available for the collection or item a default placeholder icon should be displayed.

**Comment by jaredgalanis** [comment]
- [ ] implement templating (JavaScript or Twig) and css (2d)
- [ ] setup feature flag on items/collections (2d) - if not already done by one of the other developers (Bethany?)

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc_ui_module/pull/2
