### ISSUE TITLE
About the collection block (in the collection detail page)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#105]
About the collection block (in the collection detail page)

Acceptance criteria:
- [x] Display all available metadata on the collection resource. Display language tags, if they exist. (https://docs.google.com/document/d/1Dj3iVTYO6dx4oHSh6viu8H2S-7RXfTDGdPGO8wmul-Y/edit#)  
- [ ]  ~~Clicking newly added items sorts the list by date of addition~~ (not originated from a usecase)
- [ ] ~~Clicking link to this collection copies link to the collection to the clipboard~~ (not originated from a usecase)

**Comment by jaredgalanis** [comment]
- [ ] templating and css (2d)
- [ ] sorting by newly added (1d) - most of the work for sorting will be done in the broader search interface, this is just integration of that work
- [ ] copy link to clipboard button (1d)
- [ ] export item metadata (4d) - see https://github.com/jhu-sheridan-libraries/iDC-general/issues/108

**Comment by htpvu** [comment]
@jaredgalanis please see the first bullet point that i updated. I *think* that would add to the estimate, but let meknow if i'm wrong.
