### ISSUE TITLE
Implement Collection/Item email form modal

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#107]
Use case: https://docs.google.com/document/d/16JCMBTGlr1NQwh9tAxz28aAPxMyKuUHNBW-h2H9yjOc/edit#heading=h.irdrgv2a9uu4

Acceptance criteria:
- [x] A user can click a button and a modal appears with a submittable form (accessed from the button on the collection or item detail pages)
- [ ] Included in form data are the title of the item or collection, the URL of the item or collection and all the information entered by the user
- [ ] Form data are captured and sent to a configurable email address
- [ ] There is a requirement for captcha, so we’ll need to integrate with a captcha library (captured in this ticket https://github.com/jhu-idc/iDC-general/issues/263)
- [ ] The form can be sent to the user submitting the form to their email or they can opt-out, via a checkbox

An example implementation of a form to email in Drupal: https://www.drupal.org/node/197122

**Comment by jaredgalanis** [comment]
Timelines might be less depending on reliance with #103 
- [ ] templating and css (2d)
- [ ] adjusting form data submission for this use case as opposed the contact page (2d)

**Comment by jabrah** [comment]
Update: we've implemented this for Collection Details a while ago, however the implementation for Item Details page is still TODO
