### ISSUE TITLE
Implement export metadata modal

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#108]
Usecase: https://docs.google.com/document/d/1swOAF7tPH4wK_YD0taoV9TyaQFvGuk5sxdiwcK9ayZE/edit#

Acceptance criteria: 
- [ ] When user click “Export metadata” a modal pops up presenting all possible metadata fields that COULD be exported. 
- [ ] Each field’s label will have a check box associated with it. Checking a box indicate user’s desire to export the associated field. Fields with unchecked boxes will not be exported. 
- [ ] A link labeled “Select All” allows user to select all fields
- [ ] A link labeled “Clear Selection” allows user to un-select all the boxes
- [ ] Button labeled “Export” kicks off the exporting service. Necessary information will be passed to the Export Service (to be design) so it can export the right thing to the right place. 
- [ ] Upon the return of Export Service’s run, a file is downloaded to user’s computer.

**Comment by jabrah** [comment]
Maybe 3 days? One to get the UI in shape with styling, etc, one to integrate the export service, and another to plug it into Drupal. Presumably this will be done after the item details page, so we should know how to get access to the node's data at this point.

**Comment by jaredgalanis** [comment]
- [ ] templating and css (3d)
- [ ] request to export item metadata service and handle response (3d) 
- [ ] testing (1d)

**Comment by birkland** [comment]
This might potentially be closed, due to the fact that the exported fields are fixed, according to migrate plugin requirements.  Hanh is verifying with stakeholders

**Comment by birkland** [comment]
Verified at 6/15/2021 planning meeting that this feature does not need to be implemented
