### ISSUE TITLE
Confirm requirement for SSO

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#11]
Confirm if we need to use shib for login to Islandora, and who needs to log in.  If so, then we need to create tickets to:
* Investigate/test SSO module in Drupal
* Investigate whether we need an SP reverse proxy, or if an SP strictly in the Drupal webserver is sufficient
*  Investigate how Drupal permissions/roles relate to SP identities (i.e. do we list administrators singly?  or do we need to define a group, etc)

**Comment by birkland** [comment]
I did a little bit of digging, and here’s a brief summary:

Two possible alternatives to internal Drupal accounts are:
-	Shibboleth login module
-	LDAP login module

The advantage to the Shibboleth module is that it will allow the Islandora instance to run anywhere, i.e. it can be in Amazon AWS and not on campus.  The disadvantage is that it looks like it’s not well maintained, and has limited usage.  The Drupal 8 version of the module is still a “development” release, and there is no documentation for it.  There is documentation for the Drupal 7 version of the module, though.  

The advantage of the LDAP login module is that it is well-maintained and broadly used.  The disadvantage is that it would likely require Drupal to be on the campus network, and it’s possible that logins might need to be restricted to the on-campus network as well, but those are security questions that would need answers from the ops folks.   I have also not confirmed what sort of policy or administrative hurdles this approach has to it.

The LDAP module also exposes a lot of information that could be used for automatically assigning roles in Drupal.  Having similar information exposed via Shibboleth to Drupal is a process involving campus IT.   But anyway, it’s a technical possibility to automatically assign Drupal security roles with either module, but it seems more straightforward to do so with the LDAP module.

Additionally, if we’re not interested in the “automatic role assignment” features of LDAP or Shibboleth, I believe we can do the same thing manually.  In that scenario, an admin defines groups/roles in Drupal, assigns permissions based on, then looks up users individually in order to assign them roles.  I believe both the LDAP and Shibboleth modules work in a way such that a user is in the system and can be looked up to assign roles once they’ve logged in at least once.

If we don’t use Shibboleth or LDAP at all, then Drupal user accounts would need to be created for everybody who needs to log in, and roles manually assigned.

**Comment by birkland** [comment]
A better-maintained authentication module compatible with shibboleth
https://www.caxy.com/blog/sso-drupal-8-and-shibboleth
https://www.drupal.org/project/simplesamlphp_auth

**Comment by htpvu** [comment]
This is confirmed.
