### ISSUE TITLE
Search Facets block

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#110]
Use case: https://docs.google.com/document/d/1XlHL8W-RW8beuWTCd4XNpVnfI_m-0zIA/edit#heading=h.e6kckpi25i9p

Acceptance criteria:
- [ ] A user can filter search results via facets (year, creator, subject, resource type, publisher)
- [ ] Facets are collapsible by clicking on them
- [ ] Applying facets filter a list and take a user to the search results page
It is unclear whether these facets will need to be part of a progressively decoupled portion of the UI. It is possible that utilizing filtering through JSONAPI will be the easiest way to achieve this functionality.
These facets may be able to be separated into discrete tasks if they grow large enough individually.

**Comment by jaredgalanis** [comment]
- [x] templating and css (2d)
- [x] Investigate whether use of JSON:API for search blocks is a better solution than Solr (2d)
    - extracted into this ticket https://github.com/jhu-idc/iDC-general/issues/244
- [ ] application of search facet criteria and fetching results (4d)
- [ ] testing (2d)

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-ui-theme/pull/37
