### ISSUE TITLE
Theme taxonomy page for iDC

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#116]
THe current taxonomy page in Drupal looks like this
![Screen Shot 2020-10-09 at 3 10 58 PM](https://user-images.githubusercontent.com/11050142/95760894-92e52900-0c79-11eb-992e-42acd482ab16.png)

This tickets accounts for the work of theming and styling this page to make it look consistent with the rest of the public facing site.

**Comment by jaredgalanis** [comment]
- [ ] templating and css (2d)
