### ISSUE TITLE
Proposal for idc-isle-dc, whereby Drupal images will be published by CI/CD from that repo

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#117]
proposal for idc-isle-dc, whereby Drupal images will be published by CI/CD from that repo

this supercedes 
#59 Create and populate git repo for Drupal 
#60 Figure out how to build Drupal image

**Comment by htpvu** [comment]
proposal is here https://docs.google.com/document/d/1k14eh36faFgYy-n30WthE61F6tlKYgQxXphRVMqtwQc/edit#
