### ISSUE TITLE
Implement to ability to export citation of individual item

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#119]
extracted from https://github.com/jhu-sheridan-libraries/iDC-general/issues/111

Acceptance criteria 
- [ ]  Clicking “Download Bibliographic Information” will trigger a prompt asking user to choose between getting Bibliographic information for the **Current** page or for **the entire result set** 
- [ ] Once user makes the select, trigger the process to generate citation for selected items and download resulting file to user’s computer

**Comment by jabrah** [comment]
* Create citation service to integrate the backend service (2d)
* Add button to search UI and handle selection (1d)
* Handle downloads (1d)
* Testing (1d)

**Question**
Should we simply present these citations on screen and allow the user to copy them, to use elsewhere, or should this directly download citations as a text file?

@htpvu

**Comment by htpvu** [comment]
@jabrah should download as text file

**Comment by htpvu** [comment]
@jabrah i captured the estimate as it stands, please let me know if download as text file increase or add to it/

**Comment by jabrah** [comment]
I'd add an extra day for download

**Comment by birkland** [comment]
Katie confirmed at the latest IDC application development meeting that bulk citations are not required any more.  Single-item citations are all that are needed.
https://docs.google.com/document/d/1N5ddPxfwZzOE5ddm5OIaX53InyRNLQe2HUpXidIgTZI/edit#
