### ISSUE TITLE
Demonstrate efficacy with an exemplar test.

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#126]
Estimate: 1 day

**Comment by cyork** [comment]
https://docs.google.com/document/d/1HKCXm6AiqAf7s96YSFiHqbgbdZbQUB7a745tCrfEP1E/edit#

**Comment by noahwsmith** [comment]
You may find that this snippet does what you want: https://github.com/Islandora-Devops/isle-buildkit/blob/main/.github/workflows/push.yml#L28
