### ISSUE TITLE
Develop an ingest process

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#16]
Investigate various methods of ingest, pick one that seems like it will work for us, and document

- [x] experiment with [migrate_islandora_csv](https://github.com/Islandora/migrate_islandora_csv)
- [x] experiment with Mark Jordan's methodology (link below). 
- [x] document

**Comment by bseeger** [comment]
Ingest, overall - including how to prep data:
- https://static.sched.com/hosted_files/islandoracon2019/eb/Planning%20and%20Executing%20a%20Migration%20to%20Islandora.pdf

Presentation by Seth Shaw on ingest (similar to the way Bethany has done things so far) : https://static.sched.com/hosted_files/islandoracon2019/9d/Bulk%20Load%20via%20Migrate%20API.pdf

Presentation layer ideas:
- https://static.sched.com/hosted_files/islandoracon2019/ee/IslandoraCon%20talk.pptx

One way to ingest:
https://docs.google.com/presentation/d/12vngYiiBf6osUDBQoSNGDZMQhIgHgQnECA0s4n7C1ok/edit#slide=id.gcb9a0b074_1_0


Tool for ingest management - Islandora Workbench: 
https://docs.google.com/presentation/d/1Z_fwBz9jTvqEdvgZ1ZCfnhpZCsTRjOpo4yrA9-huXXo/edit#slide=id.p

**Comment by bseeger** [comment]
I looked at three methods of ingest and here is some documentation on those methods.  

1.  migrate_islandora_csv - https://docs.google.com/document/d/1_XMzByDuqFjyEqu-u0AcI_oNVDbteaIa1Mtk_z2NnBg/edit#

1. a custom plugin: https://docs.google.com/document/d/1aFfGO_xs-royBQskeJLZ2PWAWqhx5YQuDADAbF2xOlI/edit

1. Islandora Workbench: https://docs.google.com/document/d/1JMyLrka779yfIb358TuVwi0TuTkMnMELkjgrbqg-ND4/edit

I recommend we go with the migrate_islandora_csv methodology and have detailed a workflow in the first document above, along with where the binaries themselves might be coming from (some options).   It's the most mature method of ingest at this point and I'm hopeful of a UI to help create yaml files being created at some point.
