### ISSUE TITLE
Pick domain name

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#18]
domain names for production, staging, test

**Comment by htpvu** [comment]
So we know that the Produce will keep the name of Jscholarship. But we will still need to know if under what domain it'll be served out. This is as much a branding and marketing decision as picking the product name.

**Comment by htpvu** [comment]
Per Katie's email:

`beta.jscholarship.library.jhu.edu` for PRODUCTION

`test.beta.jscholarship.library.jhu.edu` for TEST

`stage.beta.jscholarship.library.jhu.edu` for STAGE

`sandbox.beta.jscholarship.library.jhu.edu` for SANDBOX
 
Here are the main considerations that went into this decision:
 
The DSpace version of JScholarship will coexist with the initial launch of Islandora for quite some time—at least one, if not two, years. It is unlikely that we will be able to add any more collections or content to the five pilots during this time.  We want a way to clearly distinguish between the two manifestations. 
“Beta” connotes a future, better state of JScholarship, sends a hopeful message to users.
“Beta” also resonates with “test” and “unfinished” and could lead neatly into a way of soliciting user feedback--something along the lines of “JScholarship has a new look!  Tell us what you think!” 
We will continue to promote JScholarship/DSpace during the interval between the initial launch of JScholarship/Islandora and future relaunch(es) and the one will likely point to the other for some time.
