### ISSUE TITLE
Figure out the details of metadata cleanup

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#2]
It seems apparent that the metadata in JScholarship is in need of attention.

- [ ] Who is going to do metadata cleanup?
- [ ] What process is going to be used (e.g. harvest from DSpace, then transform?)
- [ ] What sort of cleanup is going to be performed?
- [ ] How long would it take

**Comment by htpvu** [comment]
We've figure this out in a series of meeting with Michelle. the resulting tickets are tagged with "metadata" in this repo.
