### ISSUE TITLE
Review design of Tech Ingest Workflow & update the workflow diagram accordingly

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#214]
Technical ingest workflow (in draft form) is [here](https://app.lucidchart.com/invitations/accept/6ae9d2aa-4d79-4cb4-9a3d-067bc03e637c)   

For reference the associated human ingest workflow is [here](https://app.lucidchart.com/lucidchart/bd68aa64-7de5-4f49-8742-ad106f290ca4/edit?shared=true&page=0_0#).

**Comment by htpvu** [comment]
The imple approach and design for ingest got drastically simplified, using Drupal modules Migrate plus and Migration Source UI to facilitate the process. 

This ticket is no longer needed.
