### ISSUE TITLE
Set up Solr Index

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#217]
from this workplan https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by htpvu** [comment]
this work should also consider the requirements from iDC-33 to Configure Solr to index all the value fields (probably done by default if a field is indexed).  If a special field is created then ensure that solr does have all the fields information.  

(task 3 https://docs.google.com/document/d/1T7X5cuVl0sQz6LiBxE0BZLfyKbAJhAjTVfXIeF53mZM/edit#)

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by bseeger** [comment]
- [x] research Solr within Drupal context
  -  https://docs.google.com/document/d/1ZLg-JDxKpLYz4zFwBlR-WsB1M0L8acJ4g4JmpSUaAKg/edit
- [x] Set up Solr Index
  - The initial solr index work is done. 
- [x] Create 1:1 link between facet-able fields with a solr field https://github.com/jhu-idc/iDC-general/issues/232
  - there are some facet fields added, but not all the requested ones, as we aren't sure what direction we are going in for solr yet. 
- [ ] Research how to show Collections over items in a collection regardless of relevance (for example, give the collection a higher relevance then the items in the collection)  https://github.com/jhu-idc/iDC-general/issues/233
  - I have not researched this as we are not sure what direction we are going in for solr search yet.
