### ISSUE TITLE
Research a way to configure collection-scoped role

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#219]
iDC-5 (task 2)

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by bseeger** [comment]
I looked at a few options - like Group, Advanced Access, Workbench (not Islandora Workbench) and a few others.  It seems that Workbench is the best module to use going forward.
