### ISSUE TITLE
Configure Collection Admin role

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#220]
iDC-8, iDC-5, Role Matrix

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by bseeger** [comment]
Addressed in https://github.com/jhu-idc/idc-isle-dc/pull/104
