### ISSUE TITLE
ensure that collection can be edited by CA and GAs

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#221]
iDC-5 and iDC-6

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by bseeger** [comment]
completed with: https://github.com/jhu-idc/idc-isle-dc/pull/104
