### ISSUE TITLE
configure Drupal to keep revisions of Repository Items

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#223]
iDC-5: https://docs.google.com/document/d/13N8gEA1sRJTnDY4OhMp57lgcMhPKEcJCjIR_IiyEfNw/edit

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by bseeger** [comment]
Drupal is configured to keep revisions of repository items.
