### ISSUE TITLE
assign baseline-users for global admin role

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#228]
iDC-6

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by birkland** [comment]
This will be handled manually on a case-by-case basis.  See: https://github.com/jhu-idc/iDC-general/issues/62
