### ISSUE TITLE
Metadata configuration

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#229]
- [x] Configure Collection as a new content type
- [x] Update respository item content type with field information
- [x] General Site configuration for metadata (install/configure modules needed, enable JSON API (if not already), ensure RDF namespaces are accounted for).
  - [x] General configuration
  - [x]  RDF namespaces accounted for
  - [ ] JSON:API module enabled
- [x] integrate our own github repositories into the dev environment ( replacing the use of islandora_defaults and controlled_access_terms with our own forms of them)
- [x] create db snapshot for dev
- [x] get changes merged into idc-isle-dc repo

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by bseeger** [comment]
This is complete except for the JSON:API module being enable. I didn't need it and I'm not sure if other's do. If they need it I'm sure it will get enable by someone else, so I'm not worried about this ticket enabling it.

**Comment by bseeger** [comment]
PR: https://github.com/jhu-idc/idc-isle-dc/pull/28
