### ISSUE TITLE
citation generation

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#234]

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by htpvu** [comment]
Seems to be a malformed ticket.

work to design citation generation will be the out come of this ticket https://github.com/jhu-idc/iDC-general/issues/93. from there the work to implement it will be analyzed .
