### ISSUE TITLE
Configure collection content type

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#235]
To be done after export service design

- [ ] Configure Collection as a new content type
- [ ] Update respository item content type with field information
- [ ] General Site configuration for metadata (install/configure modules needed, enable JSON API (if not already), ensure RDF namespaces are accounted for).
- [ ] integrate our own github repositories into the dev environment ( replacing the use of islandora_defaults and controlled_access_terms with our own forms of them)
- [ ] get changes merged into idc-isle-dc repo and create snapshot if necessary

**Comment by cyork** [comment]
https://docs.google.com/spreadsheets/d/1Pw0GBlyxeSwZ8GYh_BWQoYOMljo8f-cGF-PzlCsWolY/edit#gid=971564334

**Comment by htpvu** [comment]
duplication of #229
