### ISSUE TITLE
Decide and document how serialization of language information for each field should look like

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#237]
extracted from iDC-33 task list (per @bseeger) here: https://docs.google.com/document/d/1T7X5cuVl0sQz6LiBxE0BZLfyKbAJhAjTVfXIeF53mZM/edit#heading=h.5bb6a2px8r6t

**Comment by bseeger** [comment]
The goal is to create how we serialize the language field data on export on fields where there is a language tag. 

Right now there are existing migrations Elliot created that import these fields with language tags.  They expect the field to look like this: 
`Sample Repository Item Abstract in English;eng|日本語のサンプルリポジトリアイテムの要約;jpn`

Where there is the field string `Sample Repository Item Abstract in English` followed by a semicolon and then the 3 character language tag.   The `|` allows for multiple values to be applied to the field, like in the example above. 

Export should match what import needs and this format is sufficient and should work in export.

**Comment by bseeger** [comment]
@htpvu  - is documentation in the ticket alone good enough? I could add this to the export document to have it there as well.

**Comment by htpvu** [comment]
no additional ticket/work required: "Based on what import expects, the setup for this field for export is pretty clear."
