### ISSUE TITLE
ensure that the ingest process parse and capture language information for each field properly  properly

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#238]
Is dependent on the outcome of this ticket https://github.com/jhu-idc/iDC-general/issues/237. 

extracted from this tasks list https://docs.google.com/document/d/1T7X5cuVl0sQz6LiBxE0BZLfyKbAJhAjTVfXIeF53mZM/edit#

**Comment by birkland** [comment]
Is this done and/or obsolete and closeable at this point?

**Comment by birkland** [comment]
Already implemented
