### ISSUE TITLE
Produce list of metadata elements for resources

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#24]
Depends on the out come of #21 
Committee review & meet to make decision 

additional context: https://docs.google.com/document/d/1C3cA5TZLKcYsKEThITAfxS1Nc6AE8PVUeclZhNczisM/edit#

**Comment by mjanowiecki** [comment]
- [ ] Translate Digital Asset Metadata Policy into specific elements (fields like dc.type, dc.date.created) required for all Islandora repository items across collections

- [ ] Add specific elements to capture links to ArchivesSpace and Catalyst records

- [ ] Determine if we would like to make any any additional elements (outside of DAMP) required for all repository items across collections

- [ ] Determine baseline recommended/optional elements for all repository items across collections

- [ ] Compile and order elements (required, recommended, optional) included in "default" repository item input form

**Comment by mjanowiecki** [comment]
Note: Update use cases using translation of DAMP into specific elements
