### ISSUE TITLE
create a new field with string and language taxonomy term 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#240]
subsequently,

- [x] Create or find widget to do this
- [ ] Ensure the output from JSON-API end point contains all the information the front end developers needs to render the item's page
- [x] After we figure out how to tag fields, ensure that the language tags render correctly in RDF. 

from iDC-33 tasks list: https://docs.google.com/document/d/1T7X5cuVl0sQz6LiBxE0BZLfyKbAJhAjTVfXIeF53mZM/edit#

**Comment by bseeger** [comment]
This field now exists as of https://github.com/jhu-idc/idc-isle-dc/pull/28 but it needs to be change to be more specific.  The language taxonomy part is functional, but configurable and it would be nice to have the current widget more specific. This ticket can be closed once these are complete:  https://github.com/jhu-idc/idc-isle-dc/issues/36 & https://github.com/jhu-idc/idc-isle-dc/issues/37

**Comment by htpvu** [comment]
@bseeger can we updated the scope of this ticket to exclude the work in those two tickets? then we can close this tickets the end other tickets live on?
