### ISSUE TITLE
Explore flexibility of the "Title" field

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#241]
Not sure how much control we have over the “Title” field. ‘Title’ is a special field in Drupal that we generally have minimal control over.  We may not be able to add a language tag to that. In which case, we can use the Alternative Title field, maybe, to put different languages in?

from iDC-33 tasks list: https://docs.google.com/document/d/1T7X5cuVl0sQz6LiBxE0BZLfyKbAJhAjTVfXIeF53mZM/edit#

**Comment by bseeger** [comment]
Note to self:  Take a look at the `Node Title Length` module for nodes and it has a patch you can apply to update `name` length on taxonomies as well: https://www.drupal.org/project/title_length/issues/3041979
According to the taxonomy metadata setup, 2000 is a good max for the taxonomy names (most only need 255, but some need 1024 or 2000 characters.)

**Comment by bseeger** [comment]
Ekk! I thought title length was part of this ticket, so I accidentally added that in as well.  
### Length
My solution has the node title length now limited to 500 characters (was 255) and a taxonomy term name field limited to 2000 characters (was 255).  Some metadata is that is going to be stored in these fields can be large, hence the limit change. 

The length limit update will be part of an upcoming PR. 

### Language for title field on node
In our configuration we have a separate field representing the title language, as we cannot edit the Drupal field for this type of thing.    Both Collection Object and Repository Item have this field: 

![Screen Shot 2021-04-15 at 7 37 39 AM](https://user-images.githubusercontent.com/7966375/114863235-7dce8b80-9dbd-11eb-97e8-e2dfd6639672.png)

This is already in the system from a few PR's ago.

**Comment by bseeger** [comment]
Length is addressed by: https://github.com/jhu-idc/idc-isle-dc/pull/113
