### ISSUE TITLE
 Investigate whether use of JSON:API for search blocks is a better solution than Solr 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#244]
(ES 2d)

from the security stand point it would be better if we dont use solr. This ticket requests an investigation into use of JSON:API for search blocks to see if it is a feasible solution and if so, what type of work/effort implication is involved.

**Comment by htpvu** [comment]
@jaredgalanis if this is done, could you close this ticket?

**Comment by jaredgalanis** [comment]
@htpvu I'm actually still looking at a few things here. Will close by/at our meeting on Wed.

**Comment by jaredgalanis** [comment]
We're opting for using the search api built into drupal and exposing it with view REST exports for now. So closing this in favor of that approach.
