### ISSUE TITLE
Set up env for TEST

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#246]
- [x] SAML config (no blocker) 
- [x] Set up DNS - kubernetes manifest (will use mock infrastructure initially)
- [x] Set up storage bucket (Drupal, indexer) - kubernetes manifest 
- [x] Setup load balancer (entry point to the application) - controlled and created by k8s
- [x] THEN Set up http certificate
- [x] Figure out and Setup storage for saml secrets (collab with dev) 
- [x] Create Overlays (which translate local k8s manifest to cloud-appropriate k8s manifests) 0.5 day/env
- [x] DONE +0.5 day contingency 
- [x] Each new env requires addition Overlays for that env ~.5day

**Comment by derekbelrose** [comment]
SAML config has been submitted to IT@JH

**Comment by derekbelrose** [comment]
The terraform has been created to create storage, load balancers. They arent up because they are created when the kubernetes stack is created.

**Comment by jhujasonw** [comment]
SSL Certificate Request sent to IT@JH.  Will apply as soon as I get it back.  Cert requested to cover the *.digital.library.jhu.edu domain and the *.idc-kubernetes.cloud.library.jhu.edu domain.

**Comment by jhujasonw** [comment]
SSL Cert done

**Comment by jhujasonw** [comment]
SAML May not be working correctly yet in the k8s setup.  I will attempt to look at that today but I may need @derekbelrose to help with that tomorrow.

**Comment by jhujasonw** [comment]
Issue waiting on #298

**Comment by jhujasonw** [comment]
SAML issue fixed with PR: https://github.com/jhu-idc/idc-isle-dc/pull/102

test env is up and working in the cloud
