### ISSUE TITLE
Set up env for SANDBOX

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#247]
- [x] SAML config (no blocker) 
- [x] Set up DNS - kubernetes manifest (will use mock infrastructure initially)
- [x] Set up storage bucket (Drupal, indexer) - kubernetes manifest 
- [x] Setup load balancer (entry point to the application) - controlled and created by k8s
- [ ] THEN Set up http certificate
- [ ] Figure out and Setup storage for saml secrets (collab with dev) 
- [ ] Create Overlays (which translate local k8s manifest to cloud-appropriate k8s manifests) 0.5 day/env
- [ ] DONE +0.5 day contingency 
- [ ] Each new env requires addition Overlays for that env ~.5day

**Comment by derekbelrose** [comment]
SAML config has been submitted to IT@JH

**Comment by derekbelrose** [comment]
The terraform has been created to create storage, load balancers. They arent up because they are created when the kubernetes stack is created.

**Comment by jhujasonw** [comment]
Blocked by https://github.com/jhu-idc/idcApp-k8s/issues/43

**Comment by jhujasonw** [comment]
SANDBOX is up and passing preliminary checks.  Closing ticket.
