### ISSUE TITLE
set up env for PROD

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#249]
- [x] SAML config (no blocker) 
- [x] Set up DNS - kubernetes manifest (will use mock infrastructure initially)
- [x] Set up storage bucket (Drupal, indexer) - kubernetes manifest 
- [x] Setup load balancer (entry point to the application) - controlled and created by k8s
- [x] THEN Set up http certificate
- [x] Figure out and Setup storage for saml secrets (collab with dev) 
- [x] Create Overlays (which translate local k8s manifest to cloud-appropriate k8s manifests) 0.5 day/env
- [x] DONE +0.5 day contingency 
- [x] Each new env requires addition Overlays for that env ~.5day

**Comment by derekbelrose** [comment]
SAML config has been submitted to IT@JH

**Comment by derekbelrose** [comment]
The terraform has been created to create storage, load balancers. They arent up because they are created when the kubernetes stack is created.

**Comment by jhujasonw** [comment]
Blocked by https://github.com/jhu-idc/idcApp-k8s/issues/43

**Comment by jhujasonw** [comment]
PROD Instance is up and passes preliminary checks.  Closing ticket.
