### ISSUE TITLE
Create a protected ECS instance for developers to spin up demo instances for configuration verification

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#251]
until cloud instances are available for testing and progress verification, request an ECS instances that facilitate the same need.

**Comment by htpvu** [comment]
@derekbelrose sorry the ticket was not written accurately before. I've updated it according to our discussion in last week's planning meeting.

**Comment by jhujasonw** [comment]
Will stand up an EC2 instance running the docker-ce stack and Amazon Linux? 

Users to add as docker users?

**Comment by jhujasonw** [comment]
Users: Aaron and Bethany.
OS: Amazon Linux AMI (HVM / 64-bit)
Instance Type: t2.medium

**Comment by jhujasonw** [comment]
ec2 instance created: `ssh ec2-user@idc-testbed.cloud.library.jhu.edu`
Added @bseeger 's key, awaiting @birkland 's key.  

Keeping open until both verify connectivity and that they are good to go.

**Comment by jhujasonw** [comment]
@birkland and @bseeger now have access the testbed.  Closing this ticket.
