### ISSUE TITLE
Set up and run end to end test

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#254]
TODO #5 from this doc https://docs.google.com/document/d/1idUHe0mbjV7rQBanN0jpLC2FQpCPcxc3zCEah8J_QlE/edit#

**Comment by emetsger** [comment]
Partially addressed by https://github.com/jhu-idc/iDC-general/issues/254

**Comment by htpvu** [comment]
Partially addressed by https://github.com/jhu-idc/idc-isle-dc/pull/52?

**Comment by emetsger** [comment]
> Partially addressed by jhu-idc/idc-isle-dc#52?

yes, copy and paste error
