### ISSUE TITLE
test migration on test.digital.library.jhu.edu instance

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#256]
TODO#8 from the this document https://docs.google.com/document/d/1idUHe0mbjV7rQBanN0jpLC2FQpCPcxc3zCEah8J_QlE/edit# 

prerequisites include: 

- available and accessible of all binaries to be ingested
- migration definition
- migration spreadsheets
- availability of STAGE instance

**Comment by birkland** [comment]
Re-scoped to encompass correctness.  TODO:  Aaron create ticket for bulk ingest testing

**Comment by birkland** [comment]
Documentation on latest formats (especially related to export work) needed.

**Comment by birkland** [comment]
@mjanowiecki can you upload the problematic data?

**Comment by mjanowiecki** [comment]
Hi! Here are the two spreadsheets. The "test" one is a single media object, and the other is a complete media for the whole collection. 
[newsLetters_media-document_2021-06-22.csv](https://github.com/jhu-idc/iDC-general/files/6772286/newsLetters_media-document_2021-06-22.csv)
[test3.csv](https://github.com/jhu-idc/iDC-general/files/6772287/test3.csv)
