### ISSUE TITLE
Fix the IIIF viewer 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#268]
@bseeger Please add description of failure or any info you think might be helpful for fixing the bug. Thanks!

**Comment by bseeger** [comment]
When this [PR](https://github.com/jhu-idc/idc-isle-dc/pull/28) went in the IIIF viewer seemed to not be working anymore. I just tested it as of this [commit](https://github.com/jhu-idc/idc-isle-dc/commit/f9e22c4fc681162c41b411b668079d1f2f65b9c7) and it is functioning again.  Not sure what broke but closing this for now.
