### ISSUE TITLE
Ensure that OCR files are fully indexed to facilitate full text search on PDF documents

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#269]

**Comment by jabrah** [comment]
Seems to (mostly) work out-of-the-box for us already! Islandora came with a pre-defined action that will generate an "Extracted Text" derivative from an Image or PDF media under certain conditions:

* Islandora Object (repo item) MUST have model: Digital Document
* Uploaded media attached to this item MUST have media use: Original File

With these satisfied, the system _should_ run an action to generate a derivative called `<node-id>-Extracted Text.txt`. This text is automatically indexed by Solr as a field on the node (field is called something like `tm_X3b_en_field_edited_text`) and seems to be searched using general search queries.
