### ISSUE TITLE
Investigate the need to update solr to solr8

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#273]
investigate and determine whether we need to move to solr8, given the impending EOL of solr7.

outcome: informed decision on the next steps.

**Comment by birkland** [comment]
SOLR 7 is slated for EOL upon the release of SOLR 9, which is slated to be "Early 2021".  Therefore, we ought to upgrade to 8 soon.  Based on my tests, SOLR 8 is a drop-in replacement.
