### ISSUE TITLE
Misc style changes to front page, header, footer

### ISSUE THREAD

**Issue by jabrah** [jhu-idc/iDC-general#279]
Some minor issues with the theme in the current PR version

* [ ] Update page title (Digital Repositories @ JHU or similar?). This is the text that appears on the browser tab itself. Currently it just says something like "Default"
* [x] Add favicon - currently just uses Drupal's default favicon
* [x] Part of the "Digital Repositories" is supposed to be black
* [x] Look into normalizing site element responsiveness, width, etc. On some pages, including in headers/footers, some elements take the full page width, some have a max width. Breakpoints for some elements can also be looked into
  * [x] Top header (links to external library sites) shouldn't have a max width, should fill the full page width
  * [x] Need more information box may want a max width set so it doesn't get too wide?
  * [x] May want to set max width on the "card" wrapping the contact form? The white space left and right of the 
  * [x] Collection Details page - the "about the collection" block and "featured items" block take the full width of the screen, leaving lots of whitespace, whereas the search component has a max width
* [x] Search button in the header 
  * [x] needs to change cursor to pointer
  * [x] Prevent page transition when no search query is present
* [ ] Look at positioning of the search textbox in the search component, especially when there is no title on the component. At smaller screen sizes, it's sort of centered, looking a bit awkward
* [x] Facet values are centered, should be left aligned (becomes obvious at some screen sizes)

**Comment by jabrah** [comment]
Example of facet formatting that should be fixed 
![image](https://user-images.githubusercontent.com/5167587/113769444-fdd66080-96ee-11eb-98a6-00790f1d6f0d.png)

**Comment by jaredgalanis** [comment]
- [ ] only english language description should appear in the list item
