### ISSUE TITLE
Writing System Test Plan

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#283]
Write a list of tests that we will need to execute either manually or automatically to ensure system’s functioning as expected.

**Comment by htpvu** [comment]
Aaron is currently rsponding to comments and reviewing the doc. 

Wednesday 5/10 @10am: sort out the next steps --> draft tickets --> schedule time.

**Comment by htpvu** [comment]
test plan available for review https://docs.google.com/document/d/1VJhAuuUQJ4jPp3XKwMPQDq6rhiFpfPPy2WH1JNm4YVY/edit
