### ISSUE TITLE
Implement "Ask the Collection Amin" functionality on Collection Details page

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#291]
Clicking ask the collection admin opens a modal with an email form:

Use similar fields from the stand alone contact form, except fill out context information, such as collection names and type of question. 

*Need estimates*

**Comment by jabrah** [comment]
https://docs.google.com/document/d/16JCMBTGlr1NQwh9tAxz28aAPxMyKuUHNBW-h2H9yjOc/edit#heading=h.irdrgv2a9uu4

**Comment by jabrah** [comment]
* [x] Update Collection Object data model
  * [x] field_collection_contact_email text(plain) -> Email
  * [x] Test migrations to make sure it doesn't mess with anything
  * [x] Sync changes to `islandora_defaults`
* [x] Install modules:
  * drupal/contact_storage
  * drupal/contact_emails
  * drupal/contact_block
  * drupal/epp : Entity Prepopulate
* [x] Enable those modules
* [x] Create new contact form: Collection Contact/Feedback Form
  * [x] Need to add a field on the form, an Entity Reference field for Collection Object
    * [x] This field should now have an "Entity Prepopulate" configuration option, use this token: `[current-page:url:args:value:1]`
      That will tell the field to read the page URL path and grab the value at the 2nd place in the path (zero indexed). For example,
      `/node/16` will be parsed to get `16` using this token. This way we can embed the contact form in the collection details page and the collection reference will be prepopulated.
  * [x] Go to the "Manage Emails" config section, Add a new contact email. This will send a 2nd message 
    * [x] Add a subject however we want, for example 
      * [x] `Feedback for [contact_message:field_collection:entity:title]: [contact_message:subject]`
      * [x] Make sure "Append message" is checked
    * [x] Change Recipient reference to "Collection Object", it should "automagically" see the `field_collection_contact_email` Email field
    * [x] Make sure it is set to Enabled
* [x] Modify the theme to add a new "Modal" region
* [x] Drop the contact form into a block and place it in the new region
  * [x] Enable it only on Collection detail pages
* [x] Do some JS stuff to toggle the things

**Comment by jabrah** [comment]
Implemented here: https://github.com/jhu-idc/idc-isle-dc/pull/92
