### ISSUE TITLE
Characterize the system via testing relevant edge cases

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#292]
context document https://docs.google.com/document/d/1KqQZiSe2QSonqPKH7X7u89JdFfuqLC-CMONeneLSEoY/edit (risk  number 5)

TO deal with system resource constraints, Test the most problematic scenarios to characterize the system, which provide information about system resource requirements 
- Identify problematic scenarios to be tested (large files, concurrent ingests - with different types of media)
- Design the tests
- define/plan how to capture the system characteristics during the tests
- Run the tests/capture characteristics in Dev Env (with the most powerful system config)
- Run the same tests in one of the cloud envs.
- Provide  information gathered.

**Comment by birkland** [comment]
See also:
* [Characterize system requirements for ingesting large files](https://github.com/jhu-idc/idc-isle-dc/issues/91)
* [Characterize parallelization of derivative generation](https://github.com/jhu-idc/idc-isle-dc/issues/93)

**Comment by birkland** [comment]
This doc captures the issues at play, and provides a recommended methodology:  https://docs.google.com/document/d/1IunoC6tmJkABdF-KRKyux3WdK5dJiG67y-yuDYxFyOI/edit#
