### ISSUE TITLE
Define snapshot that will seed initial cloud instances

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#295]
Cloud instance of IDC will be able to start up from an initial "snapshot" state.  Currently, this seed content is derived from the snapshot image indicated by the `SNAPSHOT_IMAGE` value in `.env` from the tip of `idc-isle-dc` development branch. 

When we are ready to start seeding/bootstrapping cloud instances "for real", we need to get on the same page of exactly which snapshot image is used for this image, and what it needs to contain.  Thus, this task involves:

* Define the content we want in the the snapshot image used for this purpose (an empty, initialized stack state?  The content of the idc-isle-dc snapshot image at a specific point in time?  pre-loaded/migrated taxonomy values?) 
  * Do note that the current idc-isle-dc snapshot images does have some taxonomies that were migrated _manually_.  In particular, we know that contact-form-email was added manually to she snapshot, as well as access rights taxonomy values.  
* Define how we want to identify/tag this image
* Decide what the relationship between this image and the development environment will be

**Comment by derekbelrose** [comment]
I am setting this as a todo for this week for me only, not for anyone else's work. I am going to try to align this snapshot process with our backup/restore work. This will, also, allow us to create a script to facilitate creating initial data loads.

**Comment by bseeger** [comment]
Initial content we need is for cloud instances, in order for the system to behave correctly are as follows: 

- contact email migration data
- Islandora Display Taxonomy
- Islandora Media Use Taxonomy
- Islandora Models

@birkland Should I create a way for these to be run automatically on a clean install, or just create an image that has the necessary, required content in it? 

The Islandora taxonomies above are installed when the ISLE stack starts up.

**Comment by birkland** [comment]
@bseeger The original thought was to make these run on a clean install, but I think we should see if we can just get away with a stripped down image, given the time constraints

**Comment by bseeger** [comment]
I created and pushed this snapshot: 

`SNAPSHOT_TAG=upstream-20201007-739693ae-405-g521b43f.1630684249`

It has the contact form information in it as well as terms in the Islandora Models, Media Use and Display taxonomies. 

I removed all other terms and a few superfluous users.
