### ISSUE TITLE
SAML integration with JHU's IDP does not work

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#298]
The test site currently does not successfully integrate with JHU's IDP
https://test.digital.library.jhu.edu 

The net result is an error page
![image](https://user-images.githubusercontent.com/517881/112544286-32602900-8d8d-11eb-833d-e3baba9bd876.png)

The IDP is given an obviously-incorrect URL:
`https://idp.jh.edu/idp/profile/Shibboleth/SSO?providerId=https%3A%2F%2Ftest.digital.library.jhu.edu%2Fshibboleth&shire=https%3A%2F%2Flocalhost%3A8080%2Fsimplesaml%2Fmodule.php%2Fsaml%2Fsp%2Fsaml1-acs.php%2Fdefault-sp&target=_b11ff1788795a8c48354f4d039032761f4e914459c%3Ahttps%3A%2F%2Flocalhost%3A8080%2Fsimplesaml%2Fmodule.php%2Fcore%2Fas_login.php%3FAuthId%3Ddefault-sp%26ReturnTo%3Dhttp%253A%252F%252Ftest.digital.library.jhu.edu%252Fsaml_login`

**Comment by jhujasonw** [comment]
PR Opened for this: https://github.com/jhu-idc/idc-isle-dc/pull/102

**Comment by birkland** [comment]
The original issue seems fixed, but another is in its place.  The error page originates from the IdP, but the underlying cause is not apparent at quick glance.
![image](https://user-images.githubusercontent.com/517881/115470988-3c970b00-a205-11eb-92b9-a2674708aa7b.png)

**Comment by jhujasonw** [comment]
PR merged. This issue is closed.

https://github.com/jhu-idc/idc-isle-dc/pull/102
