### ISSUE TITLE
Check mysql permission for the cloud envs

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#299]
Arbitrary users can log in and modify data in the dev env

To reproduce: log in to the `drupal_default` database using username `foo` (or anything else made up), and a password _that matches the mysql root user's password_.  It is particularly concerning that this can occur for remote connections.   For example, from the `drupal` container, you can use the `mysql` client to connect to mysql (running on the mariadb container) and gain access to the `drupal_default` container using a bogus account.

It is unclear if this will affect the cloud instances (which will use Amazon RDS), so please verify the privilege escalation in the local environment, then try the same thing in the cloud instance.

**Comment by birkland** [comment]
This appears local to the dev environment
