### ISSUE TITLE
Explore initial set of taxonomies

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#3]
Figure out the initial set of taxonomies we'll use (in fields enumerated in #1 ), how their values will be determined, and subsequently ingested into Drupal.  For example, are certain taxonomies defined by an external authority or controlled vocabulary?  Extracted from existing metadata?  etc.

- [ ] (Bethany) Gather categories of taxonomies applicable to the JHU metadata, based on JScholarship
- [ ] (Bethany) Gather existing terms from JScholarship
- [ ] (Michelle or Katie?) Metadata librarians review and update (add/edit) category and taxonomy list (including adding any external authority links or controlled vocabulary links)
- [ ] (Bethany) Create ingest for taxonomy terms
- [ ] (Bethany) Ingest

**Comment by htpvu** [comment]
@bseeger how does this ticket fold up in light of this document https://docs.google.com/document/d/1C3cA5TZLKcYsKEThITAfxS1Nc6AE8PVUeclZhNczisM/edit#heading=h.pqp90zvzrkit

Does it need to be reworded? or deprecated or kept the same?

**Comment by bseeger** [comment]
The goal of this ticket is creating an ingest of vocab (items) in each taxonomy (like what are the actual subjects, people, etc).  

I'm realizing that this is something we haven't really talked about and I'm not sure folks realize how different this might be from the past. 

For things like Subjects, we'll need to create an object for each Subject we want to use.  So if a record had "Apple" as the Subject of the record, ideally we'd create "Apple" before hand (complete with authority source) and then the repository item that reference it could simply link to it.  

We could do it where the ingests generate Subjects, and then librarians curate them more afterwards (adding authority information after the ingest).

**Comment by htpvu** [comment]
@bseeger is this ticket the same as this one https://github.com/jhu-sheridan-libraries/iDC-general/issues/22
