### ISSUE TITLE
Perform metadata clean up either outside of Dspace 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#30]
- Evaluate metadata and determine clean-up required by community/collection and by field
- Determine what clean-up can be done automatically through scripts and what needs to be done manually
- Create manual workflows & instructions and assign to metadata techs
- Create or select pre-existing scripts to clean up metadata fields
- Delete and/or merge retired-field values into remaining fields (see step 4); normalize values
- Clean up all other fields with scripts; repeat and review as needed
- Review manual work 
- Use script to merge manual work into cleaned up metadata

dependent on #21, #22, #23, #24, #25, #26, #29

Additional context: https://docs.google.com/document/d/1C3cA5TZLKcYsKEThITAfxS1Nc6AE8PVUeclZhNczisM/edit#

**Comment by bseeger** [comment]
@mjanowiecki  - please note that Islandora assumes [EDTF](https://www.loc.gov/standards/datetime/) for date / time fields right out of the box, though we could just change that to a string.  Dublin Core just wants a string. However, if EDTF format is wanted for time/date, then I think some data coming from dspace will have to be tweaked.  I don't think EDTF likes dates like this date issued of: "approximately early 1930s".

**Comment by mjanowiecki** [comment]
@bseeger  Yep, I was intending on either making changes or using another field. Will discuss more in metadata committee about what to do for these cases.
