### ISSUE TITLE
Figure out how deal with public Drupal File system

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#300]
Theme installs files to the local file system. Should this be baked into the image or should it be local state to the installation?

Possible reason this causes theme to not show up in the cloud instance, as of now.

**Comment by derekbelrose** [comment]
Do the files under /var/www/drupal/web/sites/default/files need to be persistent if we are using s3 as an endpoint for drupal storage of binaries?

**Comment by dannylamb** [comment]
Drupal is going to dump a lot of things in the public filesystem (image styles, pre-rendered twig templates, color module config, etc...) that you probably want and need to be in a volume and not baked into the image.  Things are definitely going to look a little funny without those.

**Comment by birkland** [comment]
Good to know.  So we'll just keep it as a volume and have it as part of our instance's durable state, as mounted and backed up volumes.

**Comment by birkland** [comment]
@jhujasonw @derekbelrose are there any implications on the cloud instance of this?  The mounts are already there, so that's good.  I believe these volumes might have to be part of the backup plan (though it seems the size requirements would be fairly small, if it's mostly administrative misc)

**Comment by birkland** [comment]
This can be accommodated, drupal public FS will be added to backup plan
