### ISSUE TITLE
Derivatives generation do not work in k8s instances

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#303]
At present, neither local nor cloud-based kubernetes stacks successfully generate derivatives.

Currently known issues that cause this:
~[Alpaca does not connect to ActiveMQ broker](https://github.com/jhu-idc/idcApp-k8s/issues/33)~
[islandora-idc.traefik.me does not resolve to the right place](https://github.com/jhu-idc/idcApp-k8s/issues/34)

**Comment by bseeger** [comment]
@birkland - do they not work at all or just not when objects are created?  I'm seeing an issue where they don't automatically get created when the media is added, but if I run the action manually, they work.  Not sure if something is wrong with the drupal setup in general or if I broke something locally. 

Whoops - just realized this is around k8s - I'm seeing this in the non-k8s stack.  Just sharing in case it's helpful.

**Comment by birkland** [comment]
Fixed in cloud instances, remaining work ticketed in jhu-idc/idcApp-k8s#34
