### ISSUE TITLE
Add fields on applicable resource to indicate that a file has restrict access or is downloadable

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#305]
Here is a writeup about Media Use types and file restrictions: https://docs.google.com/document/d/1n8Ay8c22hbflNFneSsKQE2gNooTD2Q4I7UrRyY1tS-s/edit#

Tasks: 
- [ ] Todo now:  Add field to indicate if the Media is Restricted Access:  field_restricted_access as boolean  (Jared was planning on doing this)

~~New ticket:~~
~~- [ ] Change ‘Preservation Master File’ name to ‘Preservation File’. Since we won’t use this, it’s probably okay to just keep~~ 
~~it as that name (?). I suggest leaving it in, though, as we might need it down the road. (vendor) (possible improvement)~~

Created Separate ticket for the above: https://github.com/jhu-idc/iDC-general/issues/362
Related to: https://github.com/jhu-idc/iDC-general/issues/363
Related to: https://github.com/jhu-idc/iDC-general/issues/364

Some of this ticket will depend on the back-end file system and how restricted that is. If it's not very restricted, we might have to do more work to make it so the restricted files are not directly accessible.

**Comment by bseeger** [comment]
You could argue that the first listed task is out of scope for this ticket.

**Comment by bseeger** [comment]
This is dependent on acceptance of https://github.com/jhu-idc/iDC-general/issues/314 first.

**Comment by bseeger** [comment]
Adding in case it's helpful:  This should have no affect on export, since we are only exporting Repository Items and Collection Objects. We do not export Media.

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/205
