### ISSUE TITLE
move idc-test-data contents into a demo/ folder

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#306]
The data in idc-test-data is not aptly named - it is not test data; it is data for developer convenience.  Place it in whatever location is implied by #307. and prefer use of the word "demo" to "test"

**Comment by bseeger** [comment]
@birkland  - so as I understand this, I'm just moving this folder and @emetsger is doing any hookups to auto load it? 

I will make sure all CSV files currently there run with the migrations in the current development branch setup.

**Comment by bseeger** [comment]
@emetsger  will be creating a module described in https://github.com/jhu-idc/iDC-general/issues/307, so it's best if he moves the files at his convenience.
