### ISSUE TITLE
Figure out how to manage system content

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#308]
Follow-up from #294 

Propose procedures, technologies, or workflows to 
a.  assure system content is present in every newly bootstrapped environment
b.  assure that _changes_ to system content can be propagated to existing IDC deployments.    

A proposed solution to (a) is using the [default content](https://www.drupal.org/project/default_content) module.  However, it appears at first glance that this solution will not address (b).  If we accept the default content module as a solution to (a), then this ticket will focus on coming up with a solution for (b).  

We know the following content is "system" managed:
* Islandora Display
* Islandora Media Use
* Islandora Models
* contact_email

The outcome of this ticket is a set of procedures, technologies, or workflows to satisfy (a) and (b).

**Comment by bseeger** [comment]
I started outlining the problem and potential solutions here:  https://docs.google.com/document/d/1HfCpsQIEERHOWmpyedzhvaZJNjinoBS9v-vi78r5YxI/edit#heading=h.5tqxqv2bi1q4

It is not complete yet.

**Comment by birkland** [comment]
Done, essentially either bake in content, or add migrations to modules.
