### ISSUE TITLE
Stakeholder review of media types and allowed filename suffixes

### ISSUE THREAD

**Issue by emetsger** [jhu-idc/iDC-general#309]
Currently Islandora allows for the following media types to be created interactively:
* Audio
* Video
* Remote Video
* Extracted Text
* General files
* Images
* Documents
* FITS Technical Metadata

![image](https://user-images.githubusercontent.com/146970/113790556-9f6daa00-970f-11eb-9b9a-fe767f52ccb8.png)

First, it probably makes sense for the stakeholders to review these media types, and assess whether or not they should be supported in an ongoing fashion (e.g., work required to develop or maintain migrations for a media type that is not used would be wasted effort).

For each of these media types there exist a set of restrictions around the names of the files being uploaded.  For example, if you want to create an Image media, the system requires that the file being uploaded end with a `.png`, `.gif`, `.jpg`, or `.jpeg` extension (note that `.tif`, `.tiff` or `.jp2` is not allowed):
![image](https://user-images.githubusercontent.com/146970/113790631-c4621d00-970f-11eb-86ba-0c13e7eb8a21.png)

In addition to reviewing the _types_ of media Islandora ought to support, the policies (i.e. the file name extensions) ought to be reviewed and updated so that they align with stakeholder expectations.

(This issue arose from implementing [media migrations](https://github.com/jhu-idc/idc-isle-dc/pull/95))

**Comment by birkland** [comment]
See Bethany's doc:
https://docs.google.com/document/d/1n8Ay8c22hbflNFneSsKQE2gNooTD2Q4I7UrRyY1tS-s/edit

**Comment by bseeger** [comment]
I can add information about Media Types to the document I wrote so we (devs and stakeholders) can all get on the same page about expectations for the Media Types we will actually use.  For example, I don't see us using Remote Video right now or in the near future.  
Michelle wrote up a [document](https://docs.google.com/document/d/1VdLnAbLf79nLqUcbzLHo5B8Esbxsry6F4-HzW-J-v1M/edit) on the file types she's seen in the dspace setup so we can get a sense of which files will be in the system and fall under which Media Type (for example Tiff files must be ingested as a File Media Type, as they are not considered a viewable image on the web and therefore not a Image in Drupal).  She also is thinking about normalizing the extensions and I can bring that documentation into the document I wrote.

**Comment by bseeger** [comment]
Here's a path forward that stake holders suggest and like: 

Keep all the Media Types but change the File one: 
 - Change File to something that indicates it's non-viewable images only (tiff, tif and jp2)
 - Change File name to something more representative of what it is. 

The dev team will talk about this on Thursday to see if there are any technical difficulties with doing this (or a clearer path).

**Comment by htpvu** [comment]
dealt with in #314
