### ISSUE TITLE
Create metadata for Science Review Collection

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#31]
The team Need more information to perform this task.

Initially please find answer to these questions: 

- How many items are in this collection? 
- Where can metadata be found, either watching the video, or other source?

Owner: Katie - organize meeting with Jordon to get answers to questions about metadata. 1 hour meeting

**Comment by htpvu** [comment]
metadata profile for this collection as agreed upon with Jordon. prepared by michelle. https://docs.google.com/document/d/1sejrnysEusZfUFm1rDlUgArAyZOjtctt7lZGk1Lv4jU/edit

**Comment by mjanowiecki** [comment]
The cleaned-up Science Review metadata can be found in this folder: https://drive.google.com/open?id=1TX6Y9Que3c4cjoxI5dFaMqrn4Kle6uGZ
