### ISSUE TITLE
Make sure we can display the Drupal system messages in the Migrate Source UI page

### ISSUE THREAD

**Issue by jabrah** [jhu-idc/iDC-general#313]
On the `/migrate_source_ui` route, system messages are not displayed, making it difficult to know if a migration has completed successfully. We firstly need to determine how feasible it would be to display the Drupal system messages, and add them to the page if possible

**Comment by htpvu** [comment]
Consequences of this: when user upload files and encouter issues, it's unclear what the issues are if th messages from Drupal aren't displayed.

**Comment by jabrah** [comment]
These messages will appear in the "Status messages" block, which currently sits in the **Highlighted** region in the theme. We'd need to add this region to our theme and the messages will appear -- Or we can move the block to another region that already exists on the page. After doing this, the messages will appear when they exist, but will be unstyled, so we'd need to add some styling.

**Comment by jaredgalanis** [comment]
Closed by https://github.com/jhu-idc/idc-isle-dc/pull/135
