### ISSUE TITLE
Inform and get acceptance from stakeholder about  a path forward for the media type, media use, filename extension usage for media in iDC via documentation.

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#314]
This document will serve to communicate our plan/ability to support certain media type, media use, and file name extensions in IDC to the relevant stake holders, namely Katie and Michelle. 

the expected out come would be an aggreement on the path forward on the issue.

**Comment by bseeger** [comment]
Here's the document: https://docs.google.com/document/d/1n8Ay8c22hbflNFneSsKQE2gNooTD2Q4I7UrRyY1tS-s/edit?ts=606f7143#

It discusses the issues brought up in https://github.com/jhu-idc/iDC-general/issues/314 and https://github.com/jhu-idc/iDC-general/issues/305

**Comment by htpvu** [comment]
addresses this issue https://github.com/jhu-idc/iDC-general/issues/309

**Comment by birkland** [comment]
Results will be implemented in #340
