### ISSUE TITLE
Provide Link to allow downloads of files associated to a repository object from the system 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#315]
the work to display bitstream download links involves configuration. Special handling may be needed to not allow user to download restricted access files. 

@birkland has experience in displaying download link, please contact him for pointers. 
@bseeger will put in metadata required to determine whether a file is restricted access in this ticket  #305

**Comment by birkland** [comment]
Hope to finish implementation week of 6/15

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/205
