### ISSUE TITLE
Implement the ability of migration workflow to support "Look up convention"

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#317]
This capability is captured/described here https://docs.google.com/document/d/1WCu8bRtLELgGGoIBuyed0-pJB1GwgPuuGeLnMbCOaMM/edit#heading=h.dwao6437w2vq 

This is the subsequent work from this ticket https://github.com/jhu-idc/iDC-general/issues/316

**Comment by birkland** [comment]
Implemented in https://github.com/jhu-idc/idc-isle-dc/pull/123
