### ISSUE TITLE
Create customization of SAML user configuration via environment variables

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#318]
Right now the SAML user -> role configuration is in a yaml configuration file in the `codebase/config/sync` directory. That means it's baked into the codebase.  This works fine for the local/dev environment, but will not function across all environments and we need a more robust setup for this that pulls values from the `.env` file (or something like this). This will allow each system to be unique in it's SAML user setup. 

This ticket is for figuring out and implementing the technical work that needs to be done to setup this type of configuration.  We need to figure out how to override the relevant configuration and document how one can configure this.  It might be through the `.env` variables and the `settings.local.php` file, but it's unclear if that will work at a first glance.

**Comment by htpvu** [comment]
needs to get done prior to cloud testing (either acceptance or usability0

**Comment by birkland** [comment]
Closed, because we will not be implementing https://github.com/jhu-idc/iDC-general/issues/62
