### ISSUE TITLE
Create idc_export_module shell

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#321]
[1 day]
- Create info file with links to dependencies 
- Create composer file
- Dependencies of the module
- Include cite-proc php dependency
- Solr dependency
- Csv export dependency
- Create path for admin page setup
- config/scheme
- Wire this up to be functional
- Create controller paths and shells for functions (4 described below)
- Integrate shell into iDC composer setup (essentially tie into iDC)

outlined in Export estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

**Comment by bseeger** [comment]
New module is at:   https://github.com/jhu-idc/idc_export
This is not in the main code branch yet.

**Comment by bseeger** [comment]
The module itself, however, is in git and integrated on my branch.  Closing this.
