### ISSUE TITLE
Implement citation creation for single repository object

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#322]
[1 day]
Returns citations for item in JSON format

outline in Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)
_Write main (Controller*) functions for (*controller might not be what we use, other options include writing an Encoder and Serializer and View to do this work)_

**Comment by birkland** [comment]
@bseeger New images with internationalization extensions have successfully built in jhu-idc/idc-isle-buildkit#66.  That PR pushed its images, you can update to `TAG=upstream-20200824-f8d1e8e-50-ga52192c` in `.env` to try them out.  If it works, please approve that PR, then I'll merge it in for real.

**Comment by bseeger** [comment]
Resolved with https://github.com/jhu-idc/idc-isle-dc/pull/219
