### ISSUE TITLE
Write Tests: Citations on repository item  * RAMP UP on TEST SETUP

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#323]
[1 day]

- Test getting citations for a single item
- ~~Check admin page - change styles requested~~

outline in Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

_Write main (Controller*) functions for (*controller might not be what we use, other options include writing an Encoder and Serializer and View to do this work)_

**Comment by bseeger** [comment]
This is completed. Some basic tests are here: https://github.com/jhu-idc/idc-isle-dc/blob/development/tests/20-export-tests/testcafe/migrate_tests.spec.js#L79
