### ISSUE TITLE
Implement Citation creation

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#324]
[2 days]

- Returns CSV file of citations in format specified on admin page

outlined in **Search page** section of Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

**Comment by birkland** [comment]
Closing this issue.  At the 6/29/2021 IDC planning meeting, Katie confirmed that single-item citation export is all we need.  
https://docs.google.com/document/d/1N5ddPxfwZzOE5ddm5OIaX53InyRNLQe2HUpXidIgTZI/edit#
