### ISSUE TITLE
Write Tests: Citations on search results

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#325]
[1 day] 

- Test getting citations for a list of items
- Check admin page - change style requested

outlined in **Search Page** section of Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

**Comment by birkland** [comment]
Closing, as bulk citations of search results is not required by stakeholders.  See:
https://docs.google.com/document/d/1N5ddPxfwZzOE5ddm5OIaX53InyRNLQe2HUpXidIgTZI/edit#
