### ISSUE TITLE
Search Page: Implement Metadata export	

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#326]
[5 days]

  - [x] Returns CSV file of metadata for specific content type passed in
  - [x] Will go through next collections to get items of content type
  - [x] Check for duplication in records exported
  - [x] Make sure that the local_id / nid issue is resolved in this ticket, as described in the research done on this ticket: https://github.com/jhu-idc/iDC-general/issues/334

outlined in **Search Page** section of Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

**Comment by bseeger** [comment]
Closed with https://github.com/jhu-idc/idc-isle-dc/pull/136
