### ISSUE TITLE
Collection Page: Implement Metadata export	

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#328]
[2 days]

- Logic mostly written for the search page, so pull in and make work for this context.  (may not need to do anything at all, since this page is a search-like page, but leave some space in case it needs to be adapted).
- Returns CSV file of metadata for specific content type passed in  
- Will go through nested collections to get items of content type. 
- Does not need to check for duplication. In theory, there is none…

outlined in **Collections Page** section of Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

**Comment by bseeger** [comment]
resolved with https://github.com/jhu-idc/idc-isle-dc/pull/136
