### ISSUE TITLE
Convert cleaned-up metadata to required ingest format

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#33]
- BLOCKER: what format this needs to be in, column names, files names, where the files should be kept; how to format repeating fields (like subject)
- Bethany will fill out the format information ticket.
- Provide sample csv with 2-3 objects and taxonomies 

Additional context: https://docs.google.com/document/d/1C3cA5TZLKcYsKEThITAfxS1Nc6AE8PVUeclZhNczisM/edit#

**Comment by bseeger** [comment]
For CSV file format:  
There is a sample CSV file here: https://github.com/bseeger/jhu_ingest_csv/blob/master/data/JHUTestIngest_1.csv

It contains a general sense of what the format needs to look like.  The column names are flexible, but I think it's easiest if we don't use weird characters or spaces.  

For repeating fields they can be put in one column with a delimiter in between entries. Here's an example of a two subjects:  "Universities and colleges--Social aspects".   The only character we should avoid as a separator is a comma.  

File names should probably not have spaces or weird characters - like brackets.  That being said, we can can normalize the file names.  How particular are we about file names staying exactly as they are in the Islandora system?

**Comment by htpvu** [comment]
@bseeger i think with the changed approached to ingestion, i've accounted the work to prepare to-be-ingested content in different tickets, specifically these tickets https://github.com/orgs/jhu-idc/projects/1?card_filter_query=label%3Aingest. so if this makes sense to you, i'dl ike to close this ticket. Please let me know.

**Comment by bseeger** [comment]
@htpvu  this makes sense to me.
