### ISSUE TITLE
Roundtrip test: Metadata Import based on export file

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#330]
[1 day]

- For Repository Item
- For Collection

outlined in **Write test** section of Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#)

**Comment by bseeger** [comment]
@birkland - I'm not sure this is of value anymore. We have a test for import and, separately, a test for export. Both function.  Changing a value and re-ingesting is really just testing ingest as a method of update.   So it might be worthwhile from that perspective.  Thoughts?

**Comment by birkland** [comment]
This test can be of value to assure that exporting and re-importing results in no net change (i.e. updates the existing object (vs creating a new one), and results in no net change.  It would be a powerful test if it can introspect into the Drupal model and assure that every field has a populated value.  To the extent that export or import depends on tweaking any code or configuration response to adding new fields (or changing existing ones), the comprehensiveness aspect would catch it if that step was omitted.

That being said, this is probably not a "critical for launch" test, as we won't be touching the model any time soon.

**Comment by bseeger** [comment]
I did create a test to round trip things. It does not do any introspection for model information, but does know the expected results, so it's at least testing against what we expect to be there.
