### ISSUE TITLE
Submit to codebase

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#331]
[2 days]

- Get PR ready
- Get snapshot?

outlined in Export Estimate document [here](https://docs.google.com/document/d/15MH_eOeACcOz8Ar6CLt_d7HnJkbYZxx1Wozp6gcmC-8/edit?ts=601b1fd6#heading=h.xjd7bq8va62u)

**Comment by birkland** [comment]
Done as of https://github.com/jhu-idc/idc-isle-dc/pull/136
