### ISSUE TITLE
Make IDC test instance password more secure

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#332]
As discussed at 4/22 developers meeting:  Use configuration/environment variables to change the Drupal admin password and change it to something more secure.  Share it with the team.

**Comment by derekbelrose** [comment]
What password do you want me to change, the admin user or the web site user?

**Comment by birkland** [comment]
Changing password via environment vars does not work, possibly can achieve this by adding a drush cmd in the init script?

**Comment by birkland** [comment]
TODO:  @jhujasonw recalls Derek making a fix involving some sort of password.  check with @derekbelrose and see if he addressed this particular issue already in an init container, or if it was something else.
