### ISSUE TITLE
Verify migration IDs can be eliminated when ingesting new objects

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#334]
The proposal from the [4/26/2021 migration IDs special topic meeting](https://docs.google.com/document/d/149K8QsGFgyfhidOkCUodODf6hs9hjbwcR8LM25AoVic/edit#heading=h.9g9id7u78z1) is as follows:
* Eliminate the current `local_id` column in spreadsheets for ingest, leaving _no_ identifier column
* For exports, _do_ populate some sort of ID column with node IDs or URIs (URIs slightly preferred on our call, but please think if this still makes sense)
* For imports/migrations of existing content (that has been imported), use the ID column to find the right nodes to update

Do research/experimentation to verify that above proposal will work as expected.

**Comment by htpvu** [comment]
@bseeger Could you update the ticket with finding? close if appropriate

**Comment by bseeger** [comment]
The short explanation is that the migration logic needs a unique way to identify all the items in the csv file.  This is done, on ingest, via the local_id column. However, when we export the data, we have access to the node id (`nid`) for the item and will include that in the exported data.  We do not have easy access to the `local_id` information. 

After doing some research and talking with folks on the iDC channel, it seems like we'll need both a `nid` and `local_id` in the ingest files, to round trip the metadata.  The `local_id` will be used during the initial ingest of data and the `nid` will be used when the data is being re-imported after an export.   Both columns will need to be present in the  spreadsheet for the migration code to be happy.  However, re-ingesting a file does not actually need the `local_id` column to be populated, just that it exist at all.  The `nid` will be what the system keys off of in an update.
