### ISSUE TITLE
Research whether revisions are necessary

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#335]

**Comment by bseeger** [comment]
Revisions are part of the requirements in iDC 5 -  https://docs.google.com/document/d/13N8gEA1sRJTnDY4OhMp57lgcMhPKEcJCjIR_IiyEfNw/edit

Revisions on Repository and Collection Items is enable already.  However, an update via a migration does not produce a revision at all.  Should we do that?

**Comment by htpvu** [comment]
Hanh chatted with Katie. Katie will talk to Michelle on 5/24 about this. 

Hanh suggested that we forgo the revisiion tracking in migration module

**Comment by birkland** [comment]
At 7/6/2021 IDC planning meeting, it was determined that revisions are _not_ a supported feature for IDC, despite revisions happening "for free" from UI.  An update via migration will erase all revision history.  This can be revisited post-launch if needed
