### ISSUE TITLE
Drupal cantaloupe URL needs to be configurable

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#336]
Drupal's cantaloupe URL is incorrect and will need to be made into an environment variable so we can configure it on a per-system basis. 

This was found on the test instance, but will be something we need to make sure is configured correctly for all the cloud instances.

**Comment by bseeger** [comment]
The setting for the IIIF server is on this page in Drupal:  `https://islandora-idc.traefik.me/admin/config/islandora/iiif`

On the cloud instance this is set incorrectly and this probably needs to be set via a variable in the `.env`, but I'm not sure how this field is filled in in the first place.

**Comment by birkland** [comment]
Setting `DRUPAL_DEFAULT_CANTALOUPE_URL` in the cloud to the proper value does work
