### ISSUE TITLE
Figure out how to handle solr config and updates

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#338]
A [recent update](https://github.com/jhu-idc/idc-isle-dc/pull/117#issuecomment-830201891) to `search_api_solr` produced a warning that solr config was out of date.  As a turned out, the module's expected solr config changed.   We have no processes to:
1. automatically detect when we need to update the solr config - without this step, you are forced to notice a warning displayed on Drupal's status page (e.g. https://test.digital.library.jhu.edu/admin/reports/status) that the index was out of date.
2. manage the solr config in a controlled fashion (right now, it's simply part of the local solr state for any site, or in the snapshot image) - Right now, we are thinking we need to bake the config into the solr image, then copy it into `/opt/solr/server/solr/ISLANDORA/conf` upon startup
3. Remember to reindex when the image is deployed, (e.g. from https://test.digital.library.jhu.edu/admin/config/search/search-api/index/default_solr_index)

Figure out and propose solutions for (1) and (2).

**Comment by htpvu** [comment]
not urgent, but should be done prior to launch

**Comment by birkland** [comment]
Resolved in https://github.com/jhu-idc/idc-isle-buildkit/pull/78  - solr config is now part of solr image.  Upon boot, the solr image will update mounted volume config  to match
