### ISSUE TITLE
Remove or change character limit on search query

### ISSUE THREAD

**Issue by jabrah** [jhu-idc/iDC-general#341]
Seems that there is a character limit of 128 on the search query that goes to our search Rest Export. Because we are using Direct query mode, we directly pass a Solr query through the search API. We currently have several pieces of the UI that are mapped onto this query parameter, we can reach this limit very fast. 

We either need to remove or change this limit on the query parameter, or we'll need to find a different approach for search.

Here's a sample of the in-progress advanced search UI. The two filters on the left as well as the arbitrary term input all feed into the query parameter.

![image](https://user-images.githubusercontent.com/5167587/117365883-f640dd80-ae8d-11eb-8b89-f199c47c7892.png)

**Comment by birkland** [comment]
If the solution lies in Drupal or its configuration, then please implement the fix.  Otherwise, if it lies elsewhere (e.g. nginx, solr config, tomcat), please identify which component needs tweaking to remove this limitation

**Comment by jordandukart** [comment]
Should be handled in https://github.com/jhu-idc/idc_ui_module/pull/19.

Bunch of discussion in Slack about this. Tested with a query term of 380 characters without any issues:

```query=A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats A super long title that repeats  AND (its_field_member_of:38)```

**Comment by birkland** [comment]
Once the fix is merged in `idc_ui_module`, a PR to jhu-idc/idc-isle-dc that updates `composer.lock` to point to the updated module should close this ticket
