### ISSUE TITLE
Investigate tracking package update options

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#344]
As specified document detailing [how to kkeep iDC updated regularly](https://docs.google.com/document/d/1DwE5gzuLIbywm_sasvSXkTckCFdmAY8E1qOOTI1Wb8o/edit), and what kinds of updates to anticipate, in particular **Base image (JUST Alpine) AND package updates** section

**Comment by htpvu** [comment]
Did not have a cycle to do this. the monitoring of package updates will need to be done manully.

**Comment by htpvu** [comment]
We wanted to get ahead of keeping the iDC stack up to date. But we have not had the bandwidth to do this. Keeping application up to date remains an issue to be solved.
