### ISSUE TITLE
Create checklist of items to check after spinning up instance

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#347]
Part of Tasks planning for pilot implementation are written up here [https://docs.google.com/document/d/1vUIRzi_kTVaorz3-aVSaGBk-xpxASqYGkvAoz8NsNmg/edit# ](https://docs.google.com/document/d/1vUIRzi_kTVaorz3-aVSaGBk-xpxASqYGkvAoz8NsNmg/edit# )

**Comment by htpvu** [comment]
duplicate of this https://github.com/jhu-idc/iDC-general/issues/349
