### ISSUE TITLE
Featured repository items section on collection page requires clearing of cache before they show up

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#348]
Note: featured collection feature works fine. 

One can mark a repository item as a `Featured Item` on it's edit page.  Then when you navigate back to its parent collection it should show up as a featured item there. 

Right now for it to show up the cache needs to be cleared.  Can we make it so one doesn't have to clear the cache? 

To reproduce:  create a collection, create a repo object with `member_of` field set to that collection. Navigate to the collection page and see that it doesn't have any featured items. Then edit the repo item, clicking on `Featured Item`.   Navigate back to the collection page and see that it's still not there.  Clear cache and see that it shows up.

**Comment by htpvu** [comment]
@jabrah is this something you can pick up?

**Comment by jabrah** [comment]
I don't know how to tackle this off the top of my head, I'd have to do some investigation
