### ISSUE TITLE
Investigate metrics reporting and display

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#351]
From [6/01/2021 IDC infra meeting](https://docs.google.com/document/d/1Z-PHL6pqs7lmZdEzOGH_-F2PM4nbMA18EYOY8iED5Kg/edit#)
Metricbeats - Is there any problem hooking metricbeats into graylog?  
* On Jason't mental list to look at 
* Elasticsearch + kibana were a bit of a nightmare to secure and make stable.  
AWS project:  OpenDistro. 
* Grayog uses ES on the backend.  Worst case, can do graylog dumps, or create separate indexes.
* One of the benefits of OpenDistro was everything was in one place, just fugly because of Kibana.
* Looks like a lot of features of Kibana are now in the commercial version of graylog.  Could have metricbeats dump into ES index.  Can graylog support building graphs of this data?
This is part of the pilot:  getting access to the logs, and time-based statistics.

**Comment by jhujasonw** [comment]
pr https://github.com/jhu-idc/idc-kubernetes/pull/42 merged, a dashboard has been created, will prompt for more feedback.
