### ISSUE TITLE
Metadata Configuration Changes

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#352]
Michelle found some scenarios in the map collection that might require us to make some configuration changes so the metadata can be more flexible to handle these scenarios. 

`Barcode` and `Library Catalog Link` fields are currently not repeatable (not multi-value fields), but because of the fact that some map objects are split up into a few objects these fields really do need to be repeatable, as one item (map) might have multiple barcodes/catalog links associated with it. 

From Michelle:

> One that note, this has brought up a metadata issues. Right now, we have the Item Barcode and Library Catalog Link as Not Repeatable, but due to really bizarre cataloging where a split map is sometimes cataloged as two separate items, there might be instances where we do in fact need to repeat these fields. I wasn’t sure if our decisions on repeatability for those fields was hard coded, so I wanted to bring that to your attention, because I think we will have to change that. 

Tasks
- [x] In the Repository Item (islandora_object) content type, update the Barcode field to be repeatable
- [x] In the Repository Item (islandora_object) content type, update the Library Catalog Link field to be repeatable
- [x] In the Repository Item (islandora_object) content type, update the Finding Aid field to be repeatable. 
- [x] In the Collection Object (collection_object) content type, update the Finding Aid field to be repeatable. 
- [x] update the Repository Item's migration yml code to accept multiple values in these fields (add logic to process `|` in the field)
- [x] Update tests in 10-migration-backend-tests.sh:
     - [x] update one of the migrations to have multiple values in these fields. 
     - [x] update the verification code accordingly to check for these multiple values
- [x] Update export view to include changes to these three fields (to output multiple values for them correctly)
- [ ] ~~Update UI to display them correctly~~ - ticketed separately: #365

**Comment by bseeger** [comment]
@mjanowiecki  does this issue reflect your request?   Are there any other fields that might need changes like this?  This type of scenario wouldn't affect the finding aid, would it?   Thanks!

**Comment by mjanowiecki** [comment]
Hi Bethany, this looks right to me :) let me double check about other field changes, I'll get back to you asap. I'm not sure what you mean about finding aid?

**Comment by mjanowiecki** [comment]
Looking through the metadata, I don't think we need to change repeatability for any other fields. I know however that the Maps and Atlas collection doesn't currently have good subjects and I think we had talked about adding them at a later date. I don't necessarily though want to get rid of the requirement for subjects because I think it's important, so I was thinking of adding just like a filler subject that we can replace...

Oh, I think I know what you mean about finding aid. I don't think it impacts that field. I have that field written down as repeatable though -- is that what you have?

**Comment by birkland** [comment]
follow-up: This isn't a high-priority blocker at the moment, but is needed prior to ingesting data for real.

**Comment by bseeger** [comment]
(note that two of the tasks were marked as done, but are not done in the latest code. They may have accidentally gotten marked as done).

**Comment by bseeger** [comment]
@mjanowiecki - glad you mentioned that. I made a mistake when creating finding aid and made it a single value field.  I will add changing that to this ticket.
