### ISSUE TITLE
Change Preservation Master File to Preservation File in Media Use Taxonomy

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#362]
Change ‘Preservation Master File’ name to ‘Preservation File’ in the media use taxonomy.  

To be clear, we will not be using this particular term, but it would be good to change (at some point) to reflect changes to the [PCDM](https://pcdm.org/2021/04/09/use) vocabulary. 

Since this is not a preservation system, we don't need the term and could take it out, but not sure we need to do that right now. 

Before it's changed, it would be good to research any ripple effect it may have and if we need to change any underlying RDF mapping.   I haven't spent time looking into this, so I'm not aware how complicated (or simple!) this change might be. 

And perhaps this doesn't need to be in the launch?

**Comment by noahwsmith** [comment]
Danny says
> The name change should be fine
> if you change the URI for its external URI, you'd need to touch up some things
> b/c i think that says PreservationMaster in it as well, but still minor

I can confirm that.
