### ISSUE TITLE
Update migrations for work done for adding new field to Media objects (Restricted Access Field)

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#363]
This ticket is depending on #305 being completed first. 

- [ ] Update all the media migrations to include the new field created in #305 
- [ ] Fix the migration tests to include data in field(s) created in #305. 
- [ ] Change migration CSV files
- [ ] Change the migration tests themselves to expect said field(s).

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/205
