### ISSUE TITLE
Ensure that restricted files are not availble via direct link

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#364]
- [ ] Ensure that restricted files are not available by any direct link. 

Restricted files are Media that have the Restricted Access flag enabled. These files should not be reachable via any link directly.  They are meant to be handed out by an admin and should not be reachable by a user with less than CLA permissions.

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/205
