### ISSUE TITLE
Collection Landing page needs tweak to Finding Aid field rendering

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#365]
The fix for ticket #352 caused the Finding Aid field on the Collection Object to change from a single value to a multi-value field. 

The values for this field on the Collection Landing page are no longer rendering correctly and the underlying code needs to be updated to handle an array of values.

**Comment by bseeger** [comment]
Just to note that this can't be worked on until https://github.com/jhu-idc/idc-isle-dc/pull/176 is in.

**Comment by birkland** [comment]
Fixed in https://github.com/jhu-idc/idc-isle-dc/commit/3c74b4d704ff4ccaf303cd6dc04e335e089ba4d1 via https://github.com/jhu-idc/idc-isle-dc/pull/236
