### ISSUE TITLE
Investigate resource usage that is killing nodes in k8s

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#370]
Apparently, some process in IDC is consuming excessive resources (memory), causing that process and other processes (Including some kublet processes) to terminate.  Track down what is happening and fix

**Comment by jhujasonw** [comment]
some limits for memory have been set in https://github.com/jhu-idc/idc-kubernetes/pull/32 and https://github.com/jhu-idc/idcApp-k8s/issues/56 which close this
