### ISSUE TITLE
Expose cloud instance logs to anybody who needs it.

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#371]
Currently, IDC logs in greylog are only accessible upon request to Derek or Jason.  Expose logs so that any authorized individual (e.g. somebody in LAG, a developer, etc) can read and filter through them whenever necessary.

**Comment by jhujasonw** [comment]
Need to discuss with the ops folks about the best way to allow access to the log system.  Right now, only admin account access is allowed, but users can be created to get others access.

**Comment by jhujasonw** [comment]
An account has been created in graylog for the idc developers, login was sent to the slack channel.
