### ISSUE TITLE
Set up Drupal to use Google Analytics plugin

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#373]
* Install GTM Plugin on site, 
* Allow GTM ID to be configured via environment variable.  _do not commit the ID in any git repo_
* In GTM, create a UA tag to gather pageview information from the iDC site.
* Test setup to ensure it’s working and recording pageviews to GA.

**Comment by bseeger** [comment]
FYI - https://github.com/Islandora/documentation/issues/1887:  

> The Google Tag Manager (GTM) module (google_tags) uses conditions. When our condition forms include required fields it prevents the module from saving the GTM container configuration.

I'm not sure if this is the case for us, but when I played with a Drupal GTM plugin a while back, I was unable to save the GTM form (in drupal) that you configure the id in.  Well worth checking into this issue.
