### ISSUE TITLE
Install islandora_repository_reports for Inventory Reports

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#374]
* Install repository [module](https://github.com/mjordan/islandora_repository_reports)
* Verify that it works
* Ensure it has proper permissions for access by Global Administrator

**Comment by bseeger** [comment]
End goal for what inventory reports are available: 
https://docs.google.com/document/d/1ziU8iRyDijnPSjZR40NxWkZNKh_tb_F8FvYsFPD2fhI/edit#bookmark=id.xtv1p5z01ira
