### ISSUE TITLE
Provide/aid understanding of constraints within which the iDC site UI can be design 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#38]
Please evaluate available and usable themes for Islandora 8, and provide recommendations on them with the goal that we will be able apply our branding tweak and customization within the constraints of these themes.

**Comment by bseeger** [comment]
Here are theme options: https://docs.google.com/document/d/1zNo93GyU8bJmeO90-4BmgzJ9cbeTiVIQwFt0rUMrgbQ/edit

Here's some information on viewers and constraints: https://docs.google.com/document/d/1ol0nxrNrz-y-cM86dE81AD6C6l_MobQ9KNeuc_r7voI/edit#

**Comment by htpvu** [comment]
These document has beent made available for Jared  (in charge of UI development ) to review.
