### ISSUE TITLE
Determine reasonable resource limits for IDC containers

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#382]
As of https://github.com/jhu-idc/idcApp-k8s/pull/57, resource limits are set for k8s services.  Determine plausible resource limit values, and issue a PR to idcApp-k8s setting these values.

Will involve the results of: https://github.com/jhu-idc/iDC-general/issues/380

NB: We _should_ set these for idc-isle-dc as well

**Comment by emetsger** [comment]
Relevant details from https://docs.google.com/document/d/1IunoC6tmJkABdF-KRKyux3WdK5dJiG67y-yuDYxFyOI/edit#

Obviously, most of the time was spent with Houdini and Homarus.  If folks want more baselining from me, and if you think it is valuable information, let me know and I can run more tests locally.

# Houdini (Images)
At "rest"
PHP-FPM Master 160m (VSZ) 15m (RSS)
PHP-FPM Worker 160m (VSZ) 4m (RSS)
Nginx Master  7.9m (VSZ) 4.2m (RSS)
Nginx Worker 7.9m (VSZ) 1.8m (RSS)

Request Processing - from rest (houdini converting a 262m tiff into a thumbnail and service jpg six times)
PHP-FPM Master 160m (VSZ) 10m (RSS)
PHP-FPM Worker 161-166m (VSZ) 20-26m (RSS)
Nginx Master 8m (VSZ) 1.8m (RSS)
Nginx Worker 8.4-8.5m (VSZ) 1.3-1.4m (RSS)
Imagemagick Convert 1.5g (VSZ) 1.2g (RSS)

Request Processing - from rest (houdini converting a 441m mb tiff into a thumbnail and service jpg six times)
PHP-FPM Master 160m (VSZ) 7.4m (RSS)
PHP-FPM Worker 161-168m (VSZ) 22-30m (RSS)
Nginx Master 8m (VSZ) 1.2m (RSS)
Nginx Worker 8.4-8.5m (VSZ) 1.3-2.4m (RSS)
Imagemagick Convert 2.4g (VSZ) 2.0g (RSS)

Request Processing (houdini converting a 200kb png into a thumbnail and service jpg six times
PHP-FPM Master 160m (VSZ) 18m (RSS)
PHP-FPM Worker 161-166m (VSZ) 21-29m (RSS)
Nginx Master 8.0m (VSZ) 4.3m (RSS)
Nginx Worker 8.4m (VSZ) 1.9m (RSS)
Imagemagick Convert 68m (VSZ) 39m (RSS)

# Homarus (Video)
At "rest"
PHP-FPM Master 160m (VSZ) 18m (RSS)
PHP-FPM Worker 160m (VSZ) 4.0m (RSS)
Nginx Master  8.0m (VSZ) 4.4m (RSS)
Nginx Worker 8.4m (VSZ) 1.9m (RSS)

Request Processing (a single 4mb video)
PHP-FPM Master 160m (VSZ) 18m (RSS)
PHP-FPM Worker 160-164m (VSZ) 15-19m (RSS)
Nginx Master  8.0m (VSZ) 4.6m (RSS)
Nginx Worker 8.4m (VSZ) 1.8m (RSS)
Ffmpeg 247m (VSZ) 142-143m (RSS)
~2.5 min wall time

Request Processing (a larger 92mb video)
PHP-FPM Master 160m (VSZ) 18m (RSS)
PHP-FPM Worker 160m (VSZ) 16m (RSS)
Nginx Master  8.0m (VSZ) 4.3m (RSS)
Nginx Worker 8.4m (VSZ) 1.9m (RSS)
Ffmpeg 327m (VSZ) 213m (RSS)
~54 min wall time

# Hypercube (OCR)
Request Processing (a 99kb PDF)
Nginx Master 8.0m (VSZ) 2.5m (RSS)
Nginx Worker 8.4 (VSZ) 1.6m (RSS)
PHP-FPM Master 160m (VSZ) 12m (RSS)
PHP-FPM Worker 160m (VSZ) 4-17m (RSS)
Wall time: ~1s

# FITS service
Request Processing (a small PNG file < 100kb)
Tomcat 4.5g (VSZ) 1.3g (RSS)
Nginx Master 7.9m (VSZ) 4.1m (RSS)
Nginx Worker 8.3 (VSZ) 1.8m (RSS)
Wall time: ~1s

# Crayfits service
Request Processing (a small PNG file < 100kb)
PHP-FPM Master 160m (VSZ) 17m (RSS)
PHP-FPM Worker 160-163m (VSZ) 17-23m (RSS)
Nginx Master  8.0m (VSZ) 4.0m (RSS)
Nginx Worker 8.4m (VSZ) 1.9m (RSS)
Wall time: ~1s

**Comment by derekbelrose** [comment]
All work on this should be completed. Once we confirm the values work, I will merge the PR.
