### ISSUE TITLE
Add unique_id field to media types

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#385]
Part of overall ticket #383

- [x] Add field_unique_id to all media types
- [x] Add field_unique_id to media migration yml files,  replacing local_id with it 
- [ ]  ~~Update migration yml files to have this field as the default for parse_entity_lookup~~ #388 
- [x] Update migration tests in general and to test usage of this field

**Comment by bseeger** [comment]
@birkland adding `field_unique_id` to media is a little more complicated because of the derivatives and them having the field as well.   The services that generate the derivs do not fill in that field. (Well, yet). 

For example, when someone creates media on a node, they might add an Image Media as an Original file.  They have to fill in the unique id as well, since it's required.  When the derivatives run on that file, they do _not_ get the id (yet), as the logic that generates them does not fill that field in. 
Everything seems to work fine, but if someone edits one of the media with out the value filled in, they will not be able to save the object until they fill it in. 

I'll look at what it will take to fill in that value from the deriv services on Monday.

**Comment by birkland** [comment]
Maybe talk to Jordan about code that auto-populates that field if missing?  Possible fallbacks:  (a) do not add this field to media (if media are never referenced, and only point outwards to other entities), (b) do not mark that field as required.

**Comment by bseeger** [comment]
I was able to work this out based on Jordan's work and derivatives now have a unique id field.  All seems well.
