### ISSUE TITLE
Featured Items doesn't show items thumbnail - Tiffs

### ISSUE THREAD

**Issue by jabrah** [jhu-idc/iDC-general#392]
![image](https://user-images.githubusercontent.com/5167587/127659307-dafee3ab-f545-4bcd-b7fb-5e0216d1b6c0.png)

**Comment by jabrah** [comment]
In this example, it looks like the Mallard featured item card has an image tag pointing to `http://islandora-idc.traefik.me/system/files/2021-07/tiff_0.tif`, where the Mallard search result below it has an image tag pointed to `/system/files/2021-07/49-Thumbnail%20Image.jpg`

Could be that the Featured Item is trying to display the original Tiff instead of the thumbnail derivative?

**Comment by birkland** [comment]
Also, be aware that Drupal's 'system' thumbnails (the ones it creates internally, distinct from the thumbnails Islandora generates as a derivative) are staled-down versions _of the original format_.  So, they'd be small tiffs, not displayable by a browser.  I think we'd want the net result of this bugfix to assure the featured items are displaying the _derivative_ thumbnails for all items, which are normalized to be jpgs, I think.

**Comment by jabrah** [comment]
Adding a check for media_use of the requested image, making sure to look for Thumbnail Image seems to do the trick. Will update when I can

`idc_ui_module/src/Controller/CollectionsController.php`
``` php
      $media = \Drupal::entityTypeManager()
        ->getListBuilder('media')
        ->getStorage()
        ->loadByProperties([
          'bundle' => 'image',
          'status' => 1,
          'field_media_use' => 20,  // <=== 20 is the taxonomy ID of Media Use = Thumbnail Image
          'field_media_of' => $item_id,
        ]);
```

**Comment by birkland** [comment]
Fixed as of https://github.com/jhu-idc/idc-isle-dc/commit/48b540d90344097fbf6ead06b72d922bd61cab75 in https://github.com/jhu-idc/idc-isle-dc/pull/226
