### ISSUE TITLE
Add timeout limits as-per large file testing

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#394]
See the large file PR for environment variables that ought to be set, along with links to a related string of PRs which added new environment variables: https://github.com/jhu-idc/idc-isle-dc/pull/182.  Use the values from this and other relevant PRs to set reasonable defaults for the cloud instances.

**Comment by derekbelrose** [comment]
jhu-idc/idcApp-k8s/pull/64 fixes this.
