### ISSUE TITLE
Should have loading icon when Mirador is processing stuff

### ISSUE THREAD

**Issue by jabrah** [jhu-idc/iDC-general#395]
Currently, Mirador may take several seconds to process its data before presenting the viewer to the user. In this time, it looks like there is no media attached to a Paged Content item

**Comment by jabrah** [comment]
Would not be too difficult to add a loading icon until Mirador is initialized, but I'm not sure if this would solve the problem completely. Once Mirador is initialized, it then loads the IIIF Manifest, images, etc

**Comment by htpvu** [comment]
Fix is implemented. the resulting change still need to go into idc-isle-dc. but that'll go in along with larger changes, for ticket https://github.com/jhu-idc/iDC-general/issues/404, specifically.
