### ISSUE TITLE
Graylog alerting

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#399]
Research and develop a list of potential graylog events to alert on.

Slack is a viable and tested endpoint

**Comment by jhujasonw** [comment]
https://github.com/jhu-idc/iDC-general/issues/80 informs this issue and what could/needs to be created.

**Comment by noahwsmith** [comment]
@birkland this is the ticket that @g7morris can look into. I suspect that the outline for this work mirrors what he did with TICK for isle-7:

- Figure out what needs to be done to add Graylog to the stack, if the Ops folks haven't already done that
- Figure out how to pipe logs and other events to Graylog, if the Ops folks haven't already done that
- Figure out how to configure alerting in Graylog, and how to transmit alerts to Slack
- Create todo lists to complete implementation of the above, and discuss division of labor with the Ops folks

Who from the Ops team should he collaborate with?

**Comment by noahwsmith** [comment]
@g7morris to coordinate with @jhujasonw on this

**Comment by noahwsmith** [comment]
Ok, turns out all the bullets above are done. What this ticket actually is asking for is recommendations on what events ought to be considered for alerting. @g7morris can comment on that

**Comment by noahwsmith** [comment]
Liveness probe recommendations: https://github.com/jhu-idc/iDC-general/issues/408

**Comment by g7morris** [comment]
I would recommend the following for creating alerts:

* Certainly as @noahwsmith points out above to create alerts for all Docker container healthchecks and Liveness probes as outlined in https://github.com/jhu-idc/iDC-general/issues/408
* If the hosting server system is down or unresponsive past 30 -60 mins
* Storage disks exceeding a threshold of (75%) or being full (100%)
* If CPU usage has exceeded a threshold of (75-100%) past a certain time period e.g. 1-3 hours. 
* Check if text (keywords) on
  * a random Drupal page (e.g. About or additional content pages are still found and available every 15 -60 mins depending.
  * a specific Drupal page (e.g. an ingested object's metadata display) are still found and available every 15 -60 mins depending.
* Check ingested images urls that use IIIF to ensure the service is still up and displaying tiled images properly.

**Comment by jhujasonw** [comment]
This issue is done, jhu-idc/idcApp-k8s#83 is the implementation ticket.  Closing this one.
