### ISSUE TITLE
Gather estimates about initial size of collections

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#4]
- [x] How many items will be in each collection?
- [x] What is the aggregate size of binaries that will need to be ingested for each collection?

**Comment by bseeger** [comment]
_Note: Number of items is the repository item (not the number of binaries (files))_

- Maps and Atlases (subset from collection):
  - size: **9.6 GB**
  - number of items: **25**
- News-Letter:
  - size: **109 GB**
  - number of items: **2,728** 
- Oral Histories: 
  - size: **13 GB**
  - number of items: **93**
- Science Review: 
  - size: **709 GB**
  - number of items: **unknown**
- Graphic & Pictorial Collection
  - size: **19 GB**
  - number of items: **12,390**

**Total size:  896.6 GB of data for incoming files**

When we calculate initial disk size needs, we should keep in mind that Islandora will create a few derivatives of the files (thumbnails, service file (jpg), JP2000 in the case of an image, and OCR for PDFs). 

The numbers above come from this file: https://docs.google.com/document/d/1DOapa5n_3mFr7IfR9UoDll3Q3W75vM0SiTRV30Sm6p4/edit

Which is partially based on the data in this file: https://docs.google.com/spreadsheets/d/19sXx90uEDucn_zmgJJuNxGO3XTteLH1DGKBkEkcNAiM/edit#gid=0

**Comment by htpvu** [comment]
we've determined this for all of the initial collections except for the Maps and Atlases.

**Comment by bseeger** [comment]
Maps will be about 9.6 GB in size and contain 25 items (with multiple images each).  I've updated the above stats.
