### ISSUE TITLE
propose and document I8 instances need for this project

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#40]
We need an explicit understanding of who needs an instance of islandora 8 and for what purpose in the context of this project, ranging from sandbox to production. 

It will be important for us to share an understanding of this picture. Please talk with the team to identify needs and put together a list of instances we need to put up and maintain (at various levels), so we can start implementing them

**Comment by emetsger** [comment]
Like in PASS, we have test, demo, stage, production

**Comment by htpvu** [comment]
https://docs.google.com/document/d/1N9BLl0FZMB7XzEV5spulwxVjDhCx5obNZrpLm1R8jq0/edit
