### ISSUE TITLE
Recommend Kubernetes best practices

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#400]
Our k8s deployment is minimal.  Are there any k8s features we should leverage, but not?  Does the vendor have k8s experience, and provide recommendations or assessment of our current setup?

e.g. no autoscaling is leveraged

**Comment by derekbelrose** [comment]
BD uses turnkey solutions from GitLab to build and deploy cluster applications. Their setup is vastly different than ours.

They did say they would introduce us to their "kubernetes expert" but I have not followed up.
