### ISSUE TITLE
Collections Page: featured collection images repeat 

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#402]
On the page that lists collections (https://islandora-idc.traefik.me/collections), if a featured collection does not have an image attached to it, the image from the collection before it will repeat in its spot. 

In the image below, the first two featured collections have images associated with them, however, the third one does not.   This page ends up displaying the image from the 2nd collection for the 3rd one as well. 

![Screen Shot 2021-08-23 at 9 18 14 AM](https://user-images.githubusercontent.com/7966375/130454259-a2162eb1-f393-4203-9bf9-14d4d03a7ff1.png)

To reproduce this, create three collections, all of which have the "Featured Item" checkbox enabled. Add an Image Media to the first and/or second collection (use different images).  Do not add media to the third one.   (if you don't put an image on the 2nd _and_ 3rd, then they both end up showing up with the image from the 1st collection). 

Now check the Featured Item section of the collection list page.

**Comment by jabrah** [comment]
Looks like this is a variable scoping issue or similar, where variable values are being maintained between iterations of a for-loop that is looping through the Featured Items/Collections. I tried something as naive unsetting the variables after they're used and it looks like it solved the issue. Will propose a code change soon

Need to update these loops
https://github.com/jhu-idc/idc_ui_module/blob/main/src/Controller/CollectionsController.php#L18
https://github.com/jhu-idc/idc_ui_module/blob/main/src/Controller/CollectionsController.php#L71

**Comment by birkland** [comment]
Fixed in https://github.com/jhu-idc/idc-isle-dc/pull/226
