### ISSUE TITLE
UI polish

### ISSUE THREAD

**Issue by jabrah** [jhu-idc/iDC-general#404]
* [x] Media page styling
* [x] Contact page needs its image
* [x] style unauthorized & not found pages
* [x] style login? 
* [x] ensure `<hr />` in b/w breadcrumbs and actions toolbar or other page header bars is present in a sensible way
* [x] Use appropriate favicon
* [x] Taxonomy pages still look weird
  * There is some limitation on these pages from the current templates
* [x] Switch to prod builds for Glimmer / Tailwind
* [x] final pass on border widths and other style treatments for consistency (maybe make a tailwind util class for these things)
* [x] Enable Drupal's JS/CSS performance optimizations (get it to work)
* ~~update glimmer version~~
* [x] update tailwind version
* [x] Provide mirador loading state (see #395)
* [x] Clean up noise in logs coming from UI related things (e.g. restricted download access alter hook is doing some things causing such noise)
* [x] use transitions developed for the media download/citations modals in the contact modal
* [x] 'JHU Scholarship' link on the home page needs to be a link to JScholarship
* [x] Need a link to the homepage on all pages. Will breadcrumbs be sufficient, or should we link the top logo to the homepage?
- [x] review whole instance for titles/text blowing out of containers / behaving strangely due to length --> add line clamps where needed (noticed the featured collection title suffers from this)

**Comment by jabrah** [comment]
Note: Favicon already works

**Comment by jabrah** [comment]
So far, if we enable Drupal's "Aggregate JS files," most of the site seems to work OK, except that the Mirador viewer (for Paged Content) breaks

**Comment by jabrah** [comment]
Mirador was breaking when enabling the **Aggregate JS files** setting because of code splitting. Turning off code splitting in that package's webpack config now lets us turn on this feature.

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/275
