### ISSUE TITLE
Recommend Liveliness and Readiness checks for each Deployment

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/iDC-general#408]
Kubernetes can create livliness and readiness checks and respond accordingly based on those checks.

BD might be able to help, what are they doing for those checks? At the very least, web servers should return on non-400 HTTP codes, etc.

**Comment by derekbelrose** [comment]
#80 informs this ticket.

**Comment by noahwsmith** [comment]
And https://github.com/jhu-idc/idcApp-k8s/issues/54 should be viewed as a prereq for this task

**Comment by noahwsmith** [comment]
This can be assigned to @donRichards too

**Comment by DonRichards** [comment]
Here is the draft: https://docs.google.com/document/d/1YfjKYrCQpjxL0FO9Xsp_Af2ftVazYv23DSolC6D802U

**Comment by noahwsmith** [comment]
@birkland this is ready for review. Is this document what you expected for this task so that the next tasks ("implement the checks") can be opened? Or please leave notes in the doc for further revision from @DonRichards

**Comment by derekbelrose** [comment]
Lots of good information in that doc. Thank you for your hard work.
If @DonRichards thinks he has enough information to implement the probes, then this is sufficient.

Thanks!

**Comment by noahwsmith** [comment]
Sounds like Jason is going to evaluate whether Don's doc is sufficient to implement https://github.com/jhu-idc/idcApp-k8s/issues/54

**Comment by jhujasonw** [comment]
Looking through the document, I do not see information for the following services that we run:

- alpaca
- crayfits
- homarus
- houdini
- hypercube

Do we have any information about these?

**Comment by DonRichards** [comment]
I can add that. In a way they are related to the existing docs but I think having it in this doc would make it easier to follow and possibly bring to light some key features worth adding additional tests for.

**Comment by DonRichards** [comment]
@jhujasonw OK, that content has now been added. Please review and let me know if there's anything else I can add.

**Comment by jhujasonw** [comment]
This looks good but I am curious about the comment attached to crayfits, "Microservice that runs fits against a file. Not intended to be ran by itself. See Fits for more information." but the stack runs this container as a service and there is a port listed in the document.  Can that port be hit with an HTTP request to check it's up?

**Comment by jhujasonw** [comment]
Also Homarus has 2 ports listed and one says "Maybe, need to go back in check"  Just want to verify the right port is 8000.

**Comment by DonRichards** [comment]
@jhujasonw I don't believe crayfits has an external port associated with it. https://github.com/jhu-idc/idc-isle-dc/blob/development/docker-compose.crayfits.yml 

So I don't believe there's a endpoint exposed for it.

As for Homarus, after some looking around and speaking with Danny I was able to find an answer. Basically none of the microservices are exposed outside of the internal docker network. Although port 8000 is referenced by the build kit it isn't exposed.

**Comment by jhujasonw** [comment]
This looks like it's complete.  I will further detail the implementation details in https://github.com/jhu-idc/idcApp-k8s/issues/54  Closing this ticket
