### ISSUE TITLE
Simplified Redirects from JScholarship

### ISSUE THREAD

**Issue by jhu-alistair** [jhu-idc/iDC-general#416]
Instead of redirecting every URL currently in JScholarship for a collection to a corresponding URL in IDC, create a stub page on JSchoarlship, and take all traffic to the collection there. Stub page will explain that collection has moved.

**Comment by htpvu** [comment]
This ticket has been rewritten in a more actionable form here https://github.com/jhu-idc/iDC-general/issues/450 - assigned to @little9
