### ISSUE TITLE
Provide requirements describing user's experience in regard to URI redirect

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#42]
Each item in the new system will have 2-3 URIs  (3 if the new system has a different domain than the old one) that will be resolved to the item We need detailed, explicit requirements to inform us what the user is expected to see when each of these URIs is visited.

**Comment by isithere** [comment]
1. Do we want users to have a seamless experience—that is, no layovers from the two DSpace URIs to Islandora? 

Yes, we want users to have a seamless experience when they click on a URL from DSpace for an item now housed in Islandora. No pit stops in DSpace.
  
2. Or do we want a phased redirect, in which users would have the option to see DSpace metadata? 

 No phased redirects—too confusing, needless. 
. 
3. In Islandora, do we want to keep the distinction between the “window URL” and the “citable URI,” or just resolve to one? 

No, we do not want to keep the distinction between the window and citable URLs in the new system. One record, one URL.

**Comment by emetsger** [comment]
Amending this issue with a summary of where we have landed.  We can follow up on the iDC weekly call if there are questions or pushback on this summary.

- The http://jhir.library.jhu.edu form of URIs are deprecated.  
    - Existing JHIR URIs will continue to seamlessly resolve, either to their DSpace Item or Islandora equivalent.
        - No intervening pages when being redirected from DSpace Items to their Islandora equivalent.
        - Migrated DSpace records will not be accessible in DSpace
    - Because newly deposited J10P items automatically receive a JHIR URI, new JHIR URIs will continue to be created each time a new item is created in DSpace.
    - However, when a new item is created in Islandora (that did not previously exist in DSpace), it will _not_ have a JHIR URI.

- http://jscholarship.library.jhu.edu URIs will continue to be created each time a new Item in DSpace is created.
    - Existing JScholarship URIs will continue to seamlessly resolve, either to their DSpace Item or Islandora equivalent.
        - No intervening pages when being redirected from DSpace Items to their Islandora equivalent.
        - Migrated DSpace records will not be accessible in DSpace
    - If Islandora uses a domain name other than `jscholarship.library.jhu.edu`, then new items created in Islandora (that did not previously exist in DSpace), will _not_ have a JScholarship URI.

- For Islandora, the "window URL" is _identical_ to the "citable URI".  The window URL has both location and identifier semantics.  We would commit to the long-term support of Islandora URI resolution (just as we committed to the support of the JScholarship URIs).
    - Therefore, an item that only exists in Islandora (i.e. _not_ migrated from DSpace) will have a single URI.
    - Items that were migrated from DSpace to Islandora will have three URIs: the JHIR URI, the JScholarship URI, and the Islandora URI (assuming that Islandora uses a domain name other than `jscholarship.library.jhu.edu`)

I think an open issue is what we are going to do with respect to DSpace bitstream URLs.  We have discussed redirecting DSpace bitstream URLs to the Islandora item, and I think that represents the current consensus, but I've been out so I'm not sure if there has been an update on this.  The user experience clicking on a DSpace bitstream for a migrated DSpace item would result in a redirect to the Islandora item.  The user would need to find/navigate to the file they are interested in.

With respect to maintaining Islandora URIs, one consequence of committing to Linked Data is that we must maintain the URIs present in the "graph" of resources for an Islandora item.  So this would include the item itself, and anything it links to within Islandora, including the individual files that compose the item.  So the future user experience related to a migration from Islandora would include seamless redirects to the members of the graph (e.g. files).
