### ISSUE TITLE
FITS spinning on file on test cloud instance

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#421]
Sometimes the cloud server (test) will get into a state where crayfits will request the same file over and over every 10 seconds. 

It's log messages that seem relevant: 

(this might be irrelevant, just capturing)
```
[2021-09-28 13:08:38] request.INFO: Matched route "app_fits_exec". {"route":"app_fits_exec","route_parameters":{"_route":"app_fits_exec","_controller":"App\\Controller\\FitsController::generate_fits"},"request_uri":"http://crayfits-service:8000/","method":"GET"} []
```

This is an issue as somehow response is not populated, but it's not clear how it becomes that way: 
```
[2021-09-28 13:08:39] php.CRITICAL: Uncaught Notice: Undefined variable: response {"exception":"[object] (ErrorException(code: 0): Notice: Undefined variable: response at /var/www/crayfits/src/Controller/FitsController.php:62)"} []
```

Here's a link to the line in the crayfits code: https://github.com/roblib/CrayFits/blob/master/src/Controller/FitsController.php#L62

Clearly it expects `$response` to be legit, so there must be some unexpected error happening that doesn't cause an error to be thrown.

Here's fits failing (from graylog): 
https://graylog.idc-kubernetes.cloud.library.jhu.edu:9000/messages/graylog_35/aee00936-2060-11ec-aa63-fe1d3c156098
![Screen Shot 2021-09-28 at 9 42 27 AM](https://user-images.githubusercontent.com/7966375/135098653-f3efed6a-396f-46a3-8966-6009368e897a.png)

There's a random message in the gray log about a GET request failing that I think is coming from fits: 
![Screen Shot 2021-09-28 at 9 32 54 AM](https://user-images.githubusercontent.com/7966375/135099147-4909cade-be80-44d9-8df1-5fce2dbcc89b.png)

Side note, that crayfits code using a `post` function call that is[ deprecated in guzzle 6](https://stackoverflow.com/questions/27825667/php-guzzlehttp-how-to-make-a-post-request-with-params) - not sure if it's related or not, so just noting it. 

Here's an odd error that might be part of this: 
![Screen Shot 2021-09-28 at 9 56 23 AM](https://user-images.githubusercontent.com/7966375/135101300-9d05f715-7d30-47b4-bede-c941dbced81c.png)

**Comment by bseeger** [comment]
it is possible it's just overwhelmed and going really, really slowly, as the files being requested change slowly.  But sometimes it is the same file for a very long time (overnight).  The file is retrieved just fine, it's something on the fits end that's not processing it correctly and re-requesting it.

**Comment by dannylamb** [comment]
Looks like the underlying FITS web service is being overwhelmed.  You'll want to check the logs for that service and see if anything shows up.

Also, right above the line that's exploding in Crayfits, the variable isn't defined because of an exception getting thrown in a try/catch block https://github.com/roblib/CrayFits/blob/master/src/Controller/FitsController.php#L48-L61

In theory, based on that there should be an error message in the logs for Crayfits just before the one you took a screenshot of that might have more info.

Any way to reliably reproduce this so I can further debug?

**Comment by noahwsmith** [comment]
tagging @bseeger into this

**Comment by noahwsmith** [comment]
JHU will test this after the general "timeout extensions" task is complete, and if this is still an issue, send it back to @dannylamb with steps to replicate.

**Comment by birkland** [comment]
We're removing FITS
