### ISSUE TITLE
remove unused migrations??

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#426]
There are a few migrations that we used either initially or never. We should probably remove them from the setup as they are confusing to have there because they show up in the list of possible ingests in the Migration Source UI page. 

At the very least, these ones as we won't ever run them (or don't need, even though they might run during install?):
```
migrate_plus.migration.controlled_access_terms_language.yml
migrate_plus.migration.controlled_access_terms_rights.yml
```

And perhaps these ones as well, since we will never run them again (they are run once during install : 
```
migrate_plus.migration.islandora_defaults_tags.yml     (display hints come via this one, and resource types (don't need this one))
migrate_plus.migration.islandora_tags.yml    (models and media use taxonomy - we need this to run once upon install)
```

**Comment by mjanowiecki** [comment]
My vote (if relevant) from a user perspective is to remove them if we can :)

**Comment by htpvu** [comment]
Would be configuration fix - removing yaml files.

**Comment by htpvu** [comment]
@jaredgalanis  will do this ticket prior to launch

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/306
