### ISSUE TITLE
Metadata Export:  "value" part of quad is blank if unique_id field is not set

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#428]
The `field_title_language` showed up like this in an export: `:language::`, which is incomplete, since the value part of the quad is not set.  This was because the language taxonomy terms did not have the unique id field set (seemed like an old snapshot, since this should have been set). 

While this should technically never really happen, it was seen in the test cloud instances where the field was not set on some taxonomy terms.  (`field_unique_id` is a required field, hence this not happening unless data is messed up). 

The algorithm to create the export here should be more robust and maybe use the `name` or `title` field (depending on entity type) as a fall back for when the requested field has no value.

**Comment by htpvu** [comment]
this does not represent a possible scenario in a properly deployed system.
