### ISSUE TITLE
Search results show wrong Author information

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#432]
Right now, results display author as "admin" for each item (or whatever drupal admin ingested the item).  It should show something from the Creator/Contributor metadata not the Drupal admin user info. 

*This is a launch blocker*

@isithere will consult with @mjanowiecki and come up with a chain:  `If there's a ___ display it.  If not, look at __.  If not, look at ___.`

Once that's done we can fix the ui. 

From [requirements](https://docs.google.com/document/d/15cbz2dqNrSHXsHBvST6Cq8G86SOFSypT/edit): 
```
Question: What are the fields/information pieces of a search result item that should be displayed in the search result list?
 - Title
 - Author/Creator
 - Year (same as Facets year)
```

**Comment by htpvu** [comment]
@bseeger is this still an issue? if not could you close this?

**Comment by bseeger** [comment]
I believe it's still an issue - @jabrah can confirm. 

@isithere and @mjanowiecki  - what should be shown for author here?

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/275
