### ISSUE TITLE
SSO: role evaluation configuration change needed

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#434]
Right now the configuration for "evaluating roles each time a user logs in" is enabled.  This means that any roles assigned to the user are lost when they log out and back in again. 

Since we aren't configuring users before they log in, we need to turn this option off, so that the roles they are placed in after logging in for the first time actually stick.  (https://test.digital.library.jhu.edu/admin/config/people/simplesamlphp_auth/sync)

![Screen Shot 2021-10-11 at 3 14 50 PM](https://user-images.githubusercontent.com/7966375/136844299-6e628054-e45d-4cfe-97b3-66e1a98c832f.png)

We tweaked the configuration on the test cloud server so that Katie and Michelle could log in as themselves and have a functioning setup, but that was just a stop gap measure.  We need to tweak it in the configuration and get this into the codebase.

**Comment by bseeger** [comment]
@birkland - I was going to work on this now - since it's mission critical. I was also thinking of changing the name of the link from "Federated Login" to something else.  Just not sure of what that something else should be. "JHED Login"?

**Comment by birkland** [comment]
If it's easy, feel free to change the login text.  It's just a minor irritant to staff, compared to roles bring 💣 each login.

**Comment by bseeger** [comment]
Yup, it's super easy, so I'll toss that in.  let me know if you'd rather it be something other than `JHED Login`
