### ISSUE TITLE
Replace PV K8s output with Helm charts in Terraform

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/iDC-general#439]
We are in the process of moving away from dynamically generated kubernetes files in Terraform and using Helm charts. This reduces complexity and potential problems.

First step, remove PVs.

**Comment by derekbelrose** [comment]
This depends on jhu-library-operations/tf-mod-aws-efs-pv-k8s/issues/11 to be resolved and merged.

**Comment by htpvu** [comment]
i'm not familiar with this issue. i take the `nice-to-have` tag as this is not essential for launch. Ultimately, i think this benefits the OPS team's deployment process. But i think OPS dont have the bandwidth rightnow.
