### ISSUE TITLE
Configuration contains a hard coded link somewhere 

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#440]
At least I hope it's in configuration.... 

There is a cloud instance running and, in my current scenario, running an ingest. 

Locally, on my Mac, I am tweaking some other things and watching my local log, when I noticed this message in my log file: 
![Screen Shot 2021-11-03 at 10 04 37 AM](https://user-images.githubusercontent.com/7966375/140075530-f1027a12-0feb-4cd3-bb44-894acfcc9c0f.png)

Looks like there's a URL in configuration somewhere that needs to change to make sure the cloud servers target themselves when looking for things.

**Comment by jabrah** [comment]
Mirador in the UI is currently using hard coded absolute URLs. This PR https://github.com/jhu-idc/idc-isle-dc/pull/270 changes that to hard coded relative URLs is it at least shouldn't try to use the traefik URL

Also note, there is one more place in the UI that has this behavior -- media downloads -- that will be changed in a different PR
