### ISSUE TITLE
Create Helm Chart for Graylog

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/iDC-general#442]
Need to replace the Terraform managed Graylog instance with a Helm chart.

Do we create our own or use an already established one?

**Comment by derekbelrose** [comment]
@jhujasonw do you have any opinions on this?

**Comment by htpvu** [comment]
This ticket was meant to improve the operation of iDC and its deployment. But we no longer have the expertise and bandwidth for this. So we should spend time working on this. Once the OPS team is rebuilt. that team can review and come up with game plan for how they want to manage the operations and deployment of iDC
