### ISSUE TITLE
Bump Drupal timeouts to 7.5 minutes on test instance

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#443]
Michelle is seeing random 504 errors when uploading ~2.8 GB videos.   At the 11/9 planning meeting, we agreed to attempt to bump timeouts to 7.5 minutes, to see if the random failures disappear. 

Bump:
* The Apache reverse proxy timeout
* the `PHP_MAX_EXECUTION_TIME` timeout
* the `NGINX_FASTCGI_READ_TIMEOUT` timeout

It may be expedient just to bump all the Drupal timeouts:
"NGINX_FASTCGI_READ_TIMEOUT"
"NGINX_FASTCGI_SEND_TIMEOUT"
"NGINX_FASTCGI_CONNECT_TIMEOUT"
"NGINX_PROXY_READ_TIMEOUT"
"NGINX_PROXY_SEND_TIMEOUT"
"NGINX_PROXY_CONNECT_TIMEOUT"
"NGINX_SEND_TIMEOUT"
"NGINX_KEEPALIVE_TIMEOUT"
"NGINX_CLIENT_BODY_TIMEOUT"
"NGINX_LINGERING_TIMEOUT"

**Comment by jhujasonw** [comment]
Changes are pushed to test.
