### ISSUE TITLE
Houdini is failing on the test cloud service

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#444]
Thumbnails are not being created on the cloud test service right now (and maybe service files as well, but I didn't have a chance to check that).  It appears that houdini is not functioning correctly there, overall.  (locally, in my dev setup, it works fine). 

The following errors are being seen in the houdini logs: 

![Screen Shot 2021-11-09 at 4 25 32 PM](https://user-images.githubusercontent.com/7966375/141007445-633486d1-6b8f-48f6-8f90-b6880af9e511.png)

![Screen Shot 2021-11-09 at 4 25 50 PM](https://user-images.githubusercontent.com/7966375/141007443-12a52df4-1ab1-43d7-84ac-2e32be810c2a.png)

It's hard to tell how much of a backlog there is for work for houdini

**Comment by htpvu** [comment]
@bseeger i think we determined that this is closable. could you confirm?

**Comment by bseeger** [comment]
Yes, I think this is fixed.
