### ISSUE TITLE
 Investigate what an external UI needs to know about roles, user identity in order to enact authz

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#45]
Those who can ingest are:
- Global admins: someone who has write access to all collections in the system, is identified explicitly as part of system configuration ()
- Collection admins: someone who has write access to to specific collection. This could be captured as part of collection metadata, or maintained in separate relationship table. We haven’t decided this. Usecase for Collection Admin (not finalized) is here https://docs.google.com/document/d/13N8gEA1sRJTnDY4OhMp57lgcMhPKEcJCjIR_IiyEfNw/edit

**Comment by bseeger** [comment]
@htpvu - I think this is obsolete, since batch ingests are part of the Drupal system now.

**Comment by htpvu** [comment]
obsolete.
