### ISSUE TITLE
Re-name admin user

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#453]
Drupal has brute force protection and flood restrictions for logins built-in to core. As per the recommendations, the super user should have a different name than “admin”. Continuing, the user could be disabled altogether but dgi does not tend to do that. In dgi maintained installs the Disable User 1 Edit module is leveraged to ensure that users with valid permissions cannot revoke access.

**Comment by htpvu** [comment]
We have verified that we can log on as ourselves, with proper roles (administrator, global admin and collection admin) and be able to perform tasks privileged to our roles. 

Please proceed with changing admin user's username.

**Comment by jhujasonw** [comment]
This has been completed.
