### ISSUE TITLE
Dealing with log4j vulnerability in iDC stack

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#460]
This ticket represent the work that goes into assessing the impacts of the vulnerabilities and what we need to do to deal with it. also include work to implement the "fix"

**Comment by bseeger** [comment]
https://github.com/jhu-idc/idc-isle-buildkit/pull/100. <-- work @little9 did to upgrade Solr with a newer, safer version.

**Comment by bseeger** [comment]
[PR](https://github.com/jhu-idc/idc-isle-dc/pull/289) to integrate it with idc-isle-dc

**Comment by bseeger** [comment]
there are notes on this related [ticket](https://github.com/jhu-idc/iDC-general/issues/458).

**Comment by htpvu** [comment]
@bseeger with the above PR merged, can this ticket be closed?
