### ISSUE TITLE
Search results includes individual components (pages)

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#461]
Ideally, i want results to include collection and repository items (two content types) only.

**Comment by jabrah** [comment]
Pages (individual pages of a Paged Content item) technically are Repository Items in IDC, so we'd need to tweak the search parameters to filter them out

**Comment by htpvu** [comment]
@jabrah please let me know what kind of effort is involved. if it's too expensive, we can dodge this one.

**Comment by jabrah** [comment]
Investigating a possible solution:

Adding a filter on the REST export, if this works then the time is minimal - amounting to a Drupal config change.

(Impl reminder for myself)
![image](https://user-images.githubusercontent.com/5167587/148457660-3ea898c4-a6ca-41e9-9c85-2ff28905b335.png)
