### ISSUE TITLE
Improving ability to navigate to list of collections in the repositories

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#462]
The only place to access the list of collections right now is through the home page. Can we figure out and put a "collections" link to one of the headers (next to home) so user can get back to the list of collections without going through the home page? 

![Screen Shot 2022-01-06 at 12 30 04 PM](https://user-images.githubusercontent.com/11050142/148426495-97a5b050-43f9-4126-a8fa-05e9b6ca66fc.png)

**Comment by jabrah** [comment]
This will need some more in depth investigation. We may need to modify the built-in breadcrumb mechanism to get this to work. I think this is a module that comes from Islandora. At the moment I'm not sure if there is another (good) workaround

**Comment by jabrah** [comment]
Option: as a stop-gap, we can add another navbar with links just above/below current breadcrumbs as long as what links should appear on what pages

**Comment by jaredgalanis** [comment]
Closed by #https://github.com/jhu-idc/idc-isle-dc/pull/302
