### ISSUE TITLE
unable to send email message from the iDC interface

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#463]
Failing test case 7.4 https://docs.google.com/document/d/1UdKV_4Voe5jPU1LHEJhAi-61ngU1JHlkKtmwI7cHwo4/edit

Error message "unable to send message. contact system admin if the problem persists."

**Comment by htpvu** [comment]
Steps to replicate:

1. Visit this link https://test.digital.library.jhu.edu/node/186
2. Click "Ask the Collection Admin" button
3. Fill out the contact form, click send

<img width="1403" alt="Screen Shot 2022-01-06 at 1 51 26 PM" src="https://user-images.githubusercontent.com/11050142/148439407-278f2919-1548-4a72-bc7c-053de00d9c41.png">

**Comment by htpvu** [comment]
@jhujasonw here's some info on the email not working.

**Comment by jhujasonw** [comment]
Let me take a look and see what is happening in the container if I can figure out why it cannot send mail

**Comment by jhujasonw** [comment]
A small piece I was unaware of, in order to send mail, all the email recipents have to be verified.  I am not sure yet what exactly that means, but I will look into it more tomorrow.

**Comment by jabrah** [comment]
There's a setting requiring new users to be verified at `/admin/config/people/accounts`. No idea if it's related, but its the only thing in Drupal (core) that mentions user verification

![image](https://user-images.githubusercontent.com/5167587/150148507-1b0275a7-2b18-4420-bed2-22c3127400d9.png)

**Comment by jhujasonw** [comment]
Ah-ha! Come to find out the AWS SES (Simple Email Service) has not been taken out of sandbox mode.  When in sandbox mode, the recipients are limited to verified email addresses.  I *know* I submitted a request to have the thing taken out of sandbox mode, but it appears that it didn't happen for some reason and I did not get an email as to why.  I am submitting it again to see if I can get it setup.  Might take a day or so for AWS to approve it.

**Comment by jhujasonw** [comment]
Oh wow, that was quick and very very annoying:

```
Thank you for submitting your request to increase your sending limits. We are unable to grant your request at this time because we do not have enough information about your use case.

If you can provide additional information about how you plan to use Amazon SES, we may be able to grant your request. In your response, include as much detail as you can about your email-sending processes and procedures.

For example, tell us how often you send email, how you maintain your recipient lists, and how you manage bounces, complaints, and unsubscribe requests. It is also helpful to provide examples of the email you plan to send so we can ensure that you are sending high-quality content.
```
Can anyone help me describe in detail what type of email this thing is going to be sending?  A single sentence about sending notifications is not helpful, as that's what I put in the initial request.  I am afraid I do not know how this is going to be used so I need some input.

**Comment by bseeger** [comment]
- we will not be keeping email lists, nor will we send out group emails
- we will only have JHU affiliates logging in and we will have their email addresses in the system, but we are not going to blast them with any group email, via the system.  There is no use case for this and no infrastructure setup in the system to do this.
- these are the only scenarios where email will be sent from our system: 
  - from the "Contact Us" page - recipient: one of our admins.  We ask for name, email address, subject, message and give them the option of sending themselves a copy of the email.  We will also have the user pass a CAPTCHA test. 
  - from the "Leave Feedback or Ask an Admin" page - recipient: one of our admins. We ask for name, email address, subject, message and have them pass a CAPTCHA test before they can send it. 
- [Theoretical usage] I could see the system maybe sending a singleton email to registered users (only admins at this point - so only a handful of people) from time to time, but we have no use case for this, it's just in the realm of possibilities.  If we do send a group email to folks, it won't be from this setup, it would be outside the system (as it's currently setup). 

I can't predict how much either of the contact pages will be used, but it should be low volume and is protected from nefarious users with the CAPTCHA test.

**Comment by bseeger** [comment]
They sound like they are worried we are maintaining email lists - we will not be via this system.  We are creating paths for users to send email to the admins of our system.

**Comment by jabrah** [comment]
Only thing I can comment on is that we might want to make it clear that the contact pages (_Contact Us_ and _Leave Feedback or Ask an Admin_ forms) are publicly available, requiring only the CAPTCHA test

**Comment by htpvu** [comment]
also:
- bounced email can be sent to Lag-shared@jh.edu
- we only send email when explicitly requested by the user themselves, so we dont anticipate unsubscribed requests.
- The frequency is on demand - not on schedule.
- Emails are usually drafted by end users, content are probably question about images, video, request for access to high resolution images. We dont send templated emails. 
- Captcha features will help prevent bots activities on the email forms.

**Comment by jhujasonw** [comment]
Merging the comments from everyone, this is what I will try to send to AWS:


- we will not be keeping email lists, nor will we send out group emails
- we will only have JHU affiliates logging in and we will have their email addresses in the system, but we are not going to blast them with any group email, via the system. There is no use case for this and no infrastructure setup in the system to do this.
- these are the only scenarios where email will be sent from our system:
- from the "Contact Us" page - recipient: one of our admins determined by configuration. End user will input name, their email address, subject, message and give them the option of sending themselves a copy of the email. We will also have the user pass a CAPTCHA test.
- from the "Leave Feedback or Ask an Admin" page - recipient: one of our admins determined by configuration. End user will input name, email address, subject, message and have them pass a CAPTCHA test before they can send it.
- bounced email will be sent to a shared mailing list so that non-working emails can be removed.

**Comment by htpvu** [comment]
adding links to ticket and prs relating to email implementation for future references
https://github.com/jhu-idc/idc-isle-buildkit/pull/63 
https://github.com/jhu-idc/idcApp-k8s/pull/89 
https://github.com/jhu-idc/idcApp-k8s/issues/86

**Comment by jhujasonw** [comment]
I was just able to send a message using @htpvu example above.  I had to go in and set the FROM address in the UI for drupal, which I thought Elliot's env vars were supposed to do.  I'll double check that those env vars are set, but if they are and that value is not getting set properly, that is a bug and needs to be looked at.

It looks like my test email went to specialcollections@lists.jhu.edu

**Comment by jhujasonw** [comment]
I just checked, the test instance does have the DRUPAL_SMTP_FROM_ADDRESS set per Elliot's PR for sending mail, but the Drupal site config didn't have it set to that as the from address, which is a bug.

**Comment by htpvu** [comment]
@jhujasonw for the purpose of testing this feature on TEST, could you please set the collection Admins emails to katie's and mine? 
Maps and Atlases: hanh.vu@jhu.edu
other collections: kgucer@jhu.edu

**Comment by jhujasonw** [comment]
I do not know 100% where those get set, those should be set by someone with collection admin access to the collections you want to set them on.

**Comment by jabrah** [comment]
AFAIK the email forms should be trying to get the email addresses from the `collectionAdminContact` (or similarly named) field, set from the admin interface by anyone with the correct permissions

**Comment by htpvu** [comment]
@jhujasonw this did work with the env var work around. so i'm going to close this ticket and create a new ticket for the env var issue
