### ISSUE TITLE
update label for "Citations" button

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#465]
<img width="1403" alt="Screen Shot 2022-01-06 at 1 51 26 PM" src="https://user-images.githubusercontent.com/11050142/148439022-218ea04d-dcbe-4672-a1c3-37b648ba737d.png">

**Comment by jabrah** [comment]
Should say "View Citations" instead of just "Citations"

**Comment by jaredgalanis** [comment]
update button to say "View Citations"

**Comment by jaredgalanis** [comment]
Closed by https://github.com/jhu-idc/idc-isle-dc/pull/299

**Comment by htpvu** [comment]
verified on test instance.
