### ISSUE TITLE
No Captcha shown on Magic Eye contact form

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#466]
<img width="1438" alt="Screen Shot 2022-01-06 at 1 45 15 PM" src="https://user-images.githubusercontent.com/11050142/148439657-4e8a27e2-866a-46e2-a60b-6e596d57f198.png">

**Comment by jabrah** [comment]
For clarification: this done while not logged in?

**Comment by jabrah** [comment]
I was able to check this on `test` and the CAPTCHA did appear. As we mentioned during our meeting, the fact that a CAPTCHA had been completed before during testing may be cached somewhere in Drupal

**Comment by jabrah** [comment]
The CAPTCHA module in Drupal does have some caching built in, where it won't present the challenge to a user after they've successfully completed a challenge (for a while). This is currently set to happen for multi-step forms only, so not sure why it looks to be applied here. The setting can be found at `/admin/config/people/captcha`

**Comment by jabrah** [comment]
After another review (thanks @bseeger) it looks like this issue is that CAPTCHA appears on Collection Details page contact forms, but not on Item Details forms. Looks like this was an oversight on my part. I'll add the config to enable CAPTCHA here as soon as I can

**Comment by htpvu** [comment]
@jabrah can do this work. Has this been done ?
