### ISSUE TITLE
on a repository item detail page with media content, there was no info size and format of file

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#467]
see notes in test case 12.2 https://docs.google.com/document/d/1okQ19gJ7KVONvy5I8cI8Dz_AuGgBDHKX6VIcs6OTRhs/edit#

**Comment by jabrah** [comment]
The data of interest is metadata on the media as opposed to repository item. We'll need to investigate the best way to display media metadata in the repo item page

**Comment by htpvu** [comment]
@jabrah then let's display size on the "download media" popup up. in that pop up, format is alreayd part of the name, can we display the format there?
