### ISSUE TITLE
media download tweak

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#470]
Currently, Media download does not include PDF files and it allows downloading of different manifestation of the audio files. 

Desired behaviors:

- only present original files for download (not service file)
- present PDF files for download in the popup

<img width="1370" alt="Screen Shot 2022-01-06 at 2 53 26 PM" src="https://user-images.githubusercontent.com/11050142/148797902-de8cdcbd-5beb-49fb-973a-639b6cd53623.png">
<img width="1375" alt="Screen Shot 2022-01-06 at 2 54 53 PM" src="https://user-images.githubusercontent.com/11050142/148797944-9770314d-d31d-4a9a-907e-3e5e975e832e.png">

**Comment by jaredgalanis** [comment]
Closed by https://github.com/jhu-idc/idc-isle-dc/pull/299

**Comment by htpvu** [comment]
@jaredgalanis we verified that the requested behaviors exist.
