### ISSUE TITLE
Pages are out of order in Mirador 

### ISSUE THREAD

**Issue by bseeger** [jhu-idc/iDC-general#476]
On the sandbox there is this multi-page item that renders in Mirador: https://sandbox.digital.library.jhu.edu/node/1127

It appears that all the pages are there and it looks great (!), but the pages are out of order in the viewer. 

They are in order under the "Childrens" tab for the item. 

Upon reloading the item's view page the pages show up in a different order - so the order appears to be somewhat random.

Here are a few reload pics:
![Screen Shot 2022-01-19 at 3 11 55 PM](https://user-images.githubusercontent.com/7966375/150206479-6ee8e462-b0f5-4703-94a6-63cf5330a065.png)
![Screen Shot 2022-01-19 at 3 11 38 PM](https://user-images.githubusercontent.com/7966375/150206481-d1474577-fb0d-48e9-be3f-3338b838ca38.png)

**Comment by mjanowiecki** [comment]
All the pages are named to be in alphabetical/numeric order. Is there way to make them default sort to this?

**Comment by jabrah** [comment]
The page ordering specifically in Mirador is defined by the order of the `canvases` in the IIIF manifest. This is done in the [IDCIIIFSerializer](https://github.com/jhu-idc/idc_ui_module/blob/main/src/Plugin/views/style/IDCIIIFSerializer.php) -- we've overridden the IIIF serializer that ships with Islandora because we had already needed some custom metadata in the manifest

**Comment by jabrah** [comment]
Ah, looks like there's a sorting criteria set in the `IIIF Manifest` view in Drupal. Currently set to sort by weight

`/admin/structure/views/view/iiif_manifest`
![image](https://user-images.githubusercontent.com/5167587/150213785-672c4075-136a-4705-a1e8-2ec6d48f5585.png)

We can try changing this setting  here, or forcing an order in the IIIF serializer

**Comment by jabrah** [comment]
Looks like we can add a `weight` field to the migrations that should define the page order. We'd make the column optional, but the column would have to be added and populated in the migrations where order is important.
