### ISSUE TITLE
Make selected facets (on search pages) more visible 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#477]
<img width="380" alt="Screen Shot 2022-01-20 at 1 32 02 PM" src="https://user-images.githubusercontent.com/11050142/150401175-59be3c3d-6aeb-4930-a78b-93930af9fe6e.png">

**Comment by jabrah** [comment]
Related: we can force the selected facets to appear at the top of the list through configuration at `/admin/config/search/facets`

Each facet would have to be updated, changing Facet Sorting, Sort by active state to **Ascending** (instead of Descending)

**Comment by jabrah** [comment]
How do we want to solve this? Two main solutions off the top of my head:

1) Bring selected facets to the top of their respective lists and automatically open the facet categories that have selected values
2) Create a running list of all selected facets outside of any category. Optionally add behavior from (1)

Mockups:
![image](https://user-images.githubusercontent.com/5167587/150851101-94f142ee-cca7-4e85-b332-603f965c9893.png)

Maybe other ideas?

**Comment by htpvu** [comment]
@jabrah @jaredgalanis we're good with option1. checked with katie on Slack.

**Comment by jabrah** [comment]
Remaining work: Facet categories need to remain open when one or more value is selected. Currently, all categories close on the user. This will involve a change in our JS codebase in the theme - shouldn't be a large change

**Comment by jabrah** [comment]
Currently in test:
Selecting multiple facets in the same category will sometimes not sort selected values at the top, but sometimes will. Refreshing the page will force the facets to the top

![image](https://user-images.githubusercontent.com/5167587/159272127-282e74f5-42be-48af-9d21-57367c730631.png)
