### ISSUE TITLE
Order Years facets chronologically 

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#478]
Currently they are ordered by number of matching search results
<img width="380" alt="Screen Shot 2022-01-20 at 1 32 02 PM" src="https://user-images.githubusercontent.com/11050142/150401431-510d8308-f491-468a-bc9c-f77606263bbf.png">

**Comment by jabrah** [comment]
Looks like this can be accomplished with a facet config change in the admin interface: `/admin/config/search/facets/years/edit`
Choose display value sort order descending to make the year value sort with most recent year first in the list. Make sure to update the sort stage in advanced setting to sort first by display value before count

![image](https://user-images.githubusercontent.com/5167587/150612389-05249b86-0eba-439f-b236-30a92648f94c.png)
