### ISSUE TITLE
Advanced search does not commence at the press of ENTER/RETURN key

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#483]
reference test case 5.5 https://docs.google.com/document/d/1V7YBFVrQv18QRuEsR4FtRJDGO7-BSd113IsfGuzafgs/edit#

**Comment by jabrah** [comment]
* [x] Event handlers for advanced search currently trigger on update. Should change this to on keyup to let the interface be more reactive
* [x] Hook up search to submit search when hitting the Enter key when a search input is active
