### ISSUE TITLE
Environment variable is not being picked up by application, cause email not to work

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#489]
Specifically `DRUPAL_SMTP_FROM_ADDRESS` env var is not being utilized by the application. this prevent emails from working properly. OPS team can set this variable on running container. But this set is wiped out each time a container is restarted, leaving the feature not working again. 

For this setting to stay and email to remain working, the env var setting needs to work properly.

@jhujasonw did i word that correctly? ^^^

**Comment by jaredgalanis** [comment]
closed by https://github.com/jhu-idc/idc-isle-dc/pull/306
