### ISSUE TITLE
Find a solution for slow Drupal performance on macs

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#49]
For local development purposes, [isle-dc](https://github.com/Islandora-Devops/isle-dc) (currently used via [idc-dev](https://github.com/birkland/idc-dev)) runs Drupal in a Docker container whereby Drupal is actually installed in a local directory `codebase`, shared with the container via bind mount.  This mount is unusably  slow on macs.  Find a simple and effective recommended solution around this problem that can be recommended for mac developers, commit any necessary configuration or docker-compose files, and document the solution in [idc-dev](https://github.com/birkland/idc-dev)'s README.md

See some proposed solutions from Jeff Geerling:
https://www.jeffgeerling.com/blog/2020/revisiting-docker-macs-performance-nfs-volumes

**Comment by birkland** [comment]
Other solutions may involve eliminating/reducing the bind mount.

**Comment by htpvu** [comment]
no longer a blocking issue.
