### ISSUE TITLE
Update the UI to clarify "Search for collection(s)"

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#493]
Add help text to better explain what happen when user trigger a search from the "Search for Collection(s)" search box. 

It's unclear at first glance that this search would only be returning matching result that are of Collection object type.

**Comment by isithere** [comment]
Hi, J & J, 

Very slight change: can we change the text encircled in red to : 

_Search for collection(s) in this box._

<img width="630" alt="Screen Shot 2022-03-18 at 3 22 55 PM" src="https://user-images.githubusercontent.com/22152010/159098516-ab94bf9f-8709-4c0d-b2ca-40eca21d4de6.png">

**Comment by isithere** [comment]
Thank you!
