### ISSUE TITLE
Understand near-term growth potential of collections

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#5]
Though the initial size of collections [may be understood](https://github.com/jhu-sheridan-libraries/iDC-general/issues/4), we also need to have an estimate how big collections might grow for the next few years.   While growth over time is essentially unbounded, we need to find reasonable initial values for our initial deployment with a little room to grow before additional storage needs to be provisioned

**Comment by htpvu** [comment]
Outcome:
Initial disk space 2-3 TB 

In 1-2 years, double this dispace to 4-6TB

(see https://docs.google.com/document/d/15lOaWw5kjjkaLfUnGUS0ZUxowoPHmODVP7WZnQd9kGQ/edit for details)
