### ISSUE TITLE
Draft a data model proposal for the resources being managed by the iDC application

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#50]
This would be for the conceptual model.

the primary goal is for us to establish a shared understanding and consistent terminologies when discussing and working on the iDC application . 

Please put your work in here https://docs.google.com/document/d/13jGpuHG7Kp28zyrtc1UVh_v_eHVowQdHTuFPG_SuWGo/edit

**Comment by htpvu** [comment]
@bseeger we can fold your proposal for Collection Content Type into this ticket. 

As Could you update the above document with what the Collection Content Type would look like. What field it would have and what values would those fields have?

**Comment by bseeger** [comment]
Hi @htpvu I updated the data model document.   I put the fields in for Collection Content Type  - not sure if they are set in stone yet (and neither are the Repository Item ones - though we are close to being done). 

Here's a link to the Collection Content Type proposal, for later reference https://docs.google.com/document/d/1btUFWuS5d7LrFYkt_d5fbehnYmbv_IZdqU66A_ucRAM/edit
