### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#53]
_**LEAN Estimate**: 30 minutes, 2x multiplier_

Assuming the domain will be part of the library.jhu.edu domain, it will have to be entered into the DNS management system (efficientIP) hosted by IT@JH. This work is done by Operations and has no dependency on IT@JH other than the systems working as expected.

If we are doing something else, for example, bob.jhu.edu (note the lack of library or mse), we will need to coordinate with IT@JH and go through the process of establishing a new zone.

**Tasks**

- [ ] Log into dns.jh.edu and create CNAME records for (test|prod|dev).bob.library.jhu.edu as well as bob.library.jhu.edu.  Point these CNAMEs to their respective server endpoints. With regards to Kubernetes, all of these will point to AWS Application Load Balancers (ALBs).

**Risks**
* If the efficientIP management system is down or we do not have access to the VPN, we will be blocked. This is unavoidable on our end.
* Only Operations has access to this application. If Operations is not available, we will be blocked.

**Assumptions**
* We will be using bob.library.jhu.edu or some variant of $DOMAIN.library.jhu.edu
* We will be creating at least 3 environments (test|prod|dev).bob.library.jhu.edu with bob.library.jhu.edu pointing to prod
* We will be creating entries in both the internal and external zones, allowing DNS resolution for both the Hopkins Network (vpn, local network) and the Internet.

**Comment by derekbelrose** [comment]
DNS created for:

- test.bob.library.jhu.edu
- sandbox.bob.library.jhu.edu
- stage.bob.library.jhu.edu
- prod.bob.library.jhu.edu
- bob.library.jhu.edu
