### ISSUE TITLE
HTTPS / TLS Certificate

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#54]
_LEAN Estimate: 2.5 days, 2x multiplier_

HTTPS certificates are managed by IT@JH. The process is manually driven with Operations generating the Certificate Signing Request (CSR) and the Private Key. If we know the environments ahead of time (test, dev, production, sandbox, etc) we will only have to generate one certificate per project domain (bob.library.jhu.edu, $PROJECT_NAME.library.jhu.edu).

- [x]  Using OpenSSL commands, Operations will generate a CSR and private key
- [x]  Store the CSR and private key in a secure location
- [x]  Send CSR to IT@JH to create and sign a public key
- [x]  Download public key when it is created and store in a secure location

**Risks**
- HTTPS certificates are going to be required to be renewed annually. This is a highly time sensitive and manual task.
- Operations will need to be available to manage this process. 
- IT@JH is a dependency.  If they are not available or are unable to perform their side of the process, we are blocked.

**Assumptions**
- We know all of the environments before HTTPS CSR generation.
-  We use a known, accepted and established jhu.edu subdomain (library.jhu.edu, mse.jhu.edu)
- Operations is available to perform this work

**Comment by derekbelrose** [comment]
CSR generated and submitted to IT@JH for certificate generation.

**Comment by derekbelrose** [comment]
Certificate uploaded to ACM in the jh-msel-idc AWS Account with the ARN: arn:aws:acm:us-east-1:240722363399:certificate/65887622-6f85-4a1f-b4e8-ec01dbdb0526
