### ISSUE TITLE
Create and populate git repo for Drupal

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#59]
idc-dev currently uses [birkland/idc-drupal-site](birkland/idc-drupal-site) as a starting point for our Drupal site.  If its content is acceptable, then clone it into a git repo under our own organization.  Its origin was Islandora's demo site, which itself is a form of the default barebones Drupal site offered by Drupal.  Is the license and README appropriate?

**Expected outcome:** 
- An initial GH repo for our drupal site
- Secure an appropriate license to be included in this repo
- Create initial README

**Comment by htpvu** [comment]
https://github.com/jhu-sheridan-libraries?q=iDC-&type=&language=
