### ISSUE TITLE
Figure out how DSpace data (binaries) will be ingested

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#6]
- [ ] Where does the DSpace content exist right now, and in what form?
- [ ] Does the existing DSpace data exist in an immediately useful form, like a disk that can be mounted?
  - If not, what needs to be done in order to get it into a useful form?  Harvest and place the content in its own storage?
  - If so, what are the specific details we need to know in order to mount it where we need it?

**Comment by derekbelrose** [comment]
DSpace content is on sam.mse:/apps/dspace 

The content is like so:

> [dbelros1@msel-dspace02 assetstore]$ ls
> 10  13  16  19  22  25  28  31  34  37  40  43  46  49  52  55  58  61  64  67  70  73  76  79  82  85  88  91  94  97
> 11  14  17  20  23  26  29  32  35  38  41  44  47  50  53  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98
> 12  15  18  21  24  27  30  33  36  39  42  45  48  51  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99

> [dbelros1@msel-dspace02 assetstore]$ file 10/00/00/100000096747890320786339722131067548051
> 10/00/00/100000096747890320786339722131067548051: JPEG 2000 image data

This could be configured to be mounted on any server hosted inside the Hopkins network over NFS.

**Comment by htpvu** [comment]
duplication of https://github.com/jhu-idc/iDC-general/issues/243
