### ISSUE TITLE
Create a simple system test that can be run locally

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#63]
Figure out how to create a system test that interacts with a running local stack to verify that it minimally works.  This may involve simply doing a GET to a predetermined and pre-existing item and verifying that it is actually there.  Use your judgement as to how many tests to create.

This will involve picking a testing method of some sort, with an eye toward eventually running in CI.  The scope of this ticket includes picking the testing method - it could range from a simple bash script with CURL requests, to go-based code, to testing frameworks such as JUnit orchestrated by Maven.  Make it unburdensome and effective.  

A possible complication is having to deal with saml, if the tests encompass logging in as a known user (and thus verifying that SAML authentication works as a system test)

**Comment by derekbelrose** [comment]
Parking for now.

**Comment by htpvu** [comment]
can't be done.
