### ISSUE TITLE
Agree on stack topology

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#68]
Open up a dialogue between devs and ops.  Examine the docker-compose stack, get on the same page with respect to:

- The services running
- network topology
- environment variables
- secrets
- state (volumes, databases)

Document the stack topology as agreed upon

**Comment by htpvu** [comment]
working/outcome doc. https://docs.google.com/document/d/1RXeTGBw0Ftjbf6gaFmMJBxN6g9YzqryL4apWEoi2rwk/edit#
