### ISSUE TITLE
Figure out what subset of files will be ingested from JScholarship

### ISSUE THREAD

**Issue by birkland** [jhu-idc/iDC-general#7]
It seems that some files in JScholarship (e.g. `license.txt`) may be irrelevant and omitted from ingest.  Figure out how to determine the subset of files to ingest vs not ingest.

**Comment by htpvu** [comment]
THis has been determined, result captured in this doc https://docs.google.com/document/d/1DOapa5n_3mFr7IfR9UoDll3Q3W75vM0SiTRV30Sm6p4/edit
