### ISSUE TITLE
Get Kubernetes stack working locally (epic)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#70]
Flesh out kubernetes manifests so that the stack can run on a local workstation.  Make sure it works on mac, linux, and Windows.  Document required software and procedures necessary to get it working.

1. For every docker service (entry in docker-composer)
    - Translate into manifests for deployment and/or service in K8s → services and deployments running in K8s
    - Dev’s involvement:
        - Testing the translated “stuff”
        - Possibly co-authoring manifests
2. Remediation and integration of services and deployments to get them to talk/communicate with one another (3-4 days LE)
    - Create secrets where necessary
    - Configuration mapping
    - Dev’s involvement:
        - Testing the functional aspects
3. Replicate working stack in the next operation env (x number of operating systems).

**Comment by derekbelrose** [comment]
MacOS work to resume this week.

**Comment by jhujasonw** [comment]
WSL and Linux should be working 100% now.

**Comment by jhujasonw** [comment]
Per @birkland closing this since WSL and Linux are done and forking Mac to a new ticket labeled as nice to have for launch.
