### ISSUE TITLE
Get Kubernets stack working on cloud provider (epic)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#72]
DNS

- Ensure DNS is created for 'bob.library.jhu.edu' and it's subdomains

TLS Certificate

- Determine best way for certificate to be managed
- Generate CSR and request certificate created

Shibboleth

- Generate keypair and metadata
- Send to IT@JH for federation (incommon or just JHU)

Kubernetes manifests

- Kustomize files to patch existing Manifests to work in the cloud provider
- Access to logs for developers
- Create a role for developers to deploy to test and demo environments
- Documentation on how to access each

**Comment by jhujasonw** [comment]
@htpvu  How is this different from #73? and #85?

**Comment by htpvu** [comment]
@jhujasonw i never get these notifications! you'll have to ping me on slack or something. this is drawn from the kubernetes task planning doc https://docs.google.com/document/d/1vUIRzi_kTVaorz3-aVSaGBk-xpxASqYGkvAoz8NsNmg/edit 

i'll add some description to clarify.

**Comment by derekbelrose** [comment]
Keys and metadata generated for all domains planned (test,stage,sandbox,prod).

Requests sent to Enterprise Auth.

**Comment by jhujasonw** [comment]
All instances/namespaces of iDC are up and running in the cloud.
