### ISSUE TITLE
Stand up IDC instances

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#73]
AFTER we successfully stand up an IDC stack in the cloud, we need to stand up all the instances required by the IDC use cases (e.g. test, sandbox, stage, production, etc).  These will be open to the internet at large for viewing (and protected by SAML for edits), but existing URIs for JScholarship items will not link to anything in the production IDC for quite a while (that work is unrelated to the pilot, and thus not captured here).

**Comment by jhujasonw** [comment]
Can we include the instance names in this ticket? I thought I had seen that that was decided on.

**Comment by htpvu** [comment]
we'll need 
Sandbox
Test
Stage
Production

**Comment by jhujasonw** [comment]
@htpvu Just so I know, this is to stand up the actual IDC software in the instances and is different than #85 right?  If that is the case it's going to block until everything is ready from the devs.

**Comment by htpvu** [comment]
yes I believe this is different and blocked @jhujasonw

**Comment by jhujasonw** [comment]
all instances/namespaces of iDC are up and running
