### ISSUE TITLE
Investigate local development against Kubernetes (epic)

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#74]

**Comment by cyork** [comment]
So far, we have been using a docker-compose based [development environment](https://github.com/jhu-sheridan-libraries/iDC-general/issues/56) from ISLE (or inspired by ISLE, if we ended up not using ISLE directly).  A prior pilot task [has made local development feasible](https://github.com/jhu-sheridan-libraries/iDC-general/issues/70) using the kubernetes stack.  Now it's time to investigate local development against the kubernetes-based stack.  In particular:
Investigate whether the local kubernetes stack is technically capable of supporting the local development workflows we've been using the ISLE development environment for.  The goal of this effort is twofold:

- Understand the costs, benefits, and practical characteristics of using Kubernetes for a local development stack, using the existing ISLE-based development environment as a comparison.
- Make a decision as to whether we keep using the existing ISLE-based development environment for the duration of IDC, or whether it makes sense to

**Comment by htpvu** [comment]
we decided not to do this due to lack of time/resource.
