### ISSUE TITLE
Explore health checks, monitoring

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#80]

**Comment by cyork** [comment]
Kubernetes has some build-in capacity for re-starting services based upon results from a health check.  Determine if we should leverage any such kubernetes-native functionality.  More broadly, determine the necessary level of monitoring IDC needs.  Implementing a monitoring strategy might be out of scope for this pilot or IDC launch.  The complexity of the islandora stack adds interesting twists to this (e.g. have all derivatives been generated?)

**Comment by derekbelrose** [comment]
I suggest we break this into two separate tickets as it deal with two different issues:

1) Health Checks
2) Monitoring
