### ISSUE TITLE
Develop process for resetting sandbox

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#81]

**Comment by cyork** [comment]
From [IDC-25](https://docs.google.com/document/d/1yjmIjXM1y-9vcDHlTAcagNH3uH9c77vh9fvWRkX3RZ4/edit)

- The sandbox instance server should be reset (/reinstalled) automatically every two weeks to keep the server clean, neat, and up to date with the code base on the production system.
- When the system is refreshed, the underlying code should be synchronized with the code that the production server is using.
- Data on the sandbox instance is considered ephemeral and will get removed from time to time.  It will not carry the same data as what’s in production.  One should not expect repository items created/edited there to exist for very long.

This might be both dev + ops. It might be easier to reset the data Inside the containers then it is to rebuild the environment, especially if there's some expected default state.

**Comment by jhujasonw** [comment]
Taking a stab at this too.

This could be an automated setup where a Job manifest would run a series of commands to reset things.

Things it can/should do:

- drop the db
- empty the s3 bucket
- clear all the persistent volumes

One issue I could see is that the best way to re-initialize the namespace is to drop it, and rebuild it.  I suppose if we can re-start a Job within the cluster, we could restart the `idc-bootstrap` job and that will re-do the DB and re-install the snapshot from the S3 bucket.  The deployments should probably be stopped or the namespace dropped before that bootstrap runs.  This looks like a catch 22.

There may be a crafty way to do this via a job to drop the namespace do the above 3 tasks, and rerun kustomize from within the job via automation similar to what would be in a CD setup.  The job would have to run in a different namespace to make sure it doesn't die when the staging namespace is dropped.  The AWS auth might be the tricky part to that, but the terraform (to generate a kubeconfig) and the rest of the automation should already be there.  The AWS auth should be read only though, to make sure it's not poking at things it shouldn't be.  It may require that the AWS auth have perms to the cluster though, to make sure it can create resources.

This could dovetail with CI/CD if done the "crafty" way.

**Comment by derekbelrose** [comment]
AWS auth might not be needed because pods are considered part of the cluster. Using RBAC, we should be able to give a deployment, job, service, etc the rights needed to delete and recreate stuff. I think it running the `idc-bootstrap` job and then killing the drupal pod should be enough. I think we should test this.

**Comment by jhujasonw** [comment]
I think the only thing might be whipping up the kubeconfig file to actually access the cluster from within the cluster.  It might be that the cron service creates some sort of service account on the cluster?  This is something I haven't done yet, but would like to look into.

Edit: This seems like an interesting start: https://itnext.io/running-kubectl-commands-from-within-a-pod-b303e8176088

**Comment by birkland** [comment]
The sandbox will start off empty for launch, so no content is needed.  An empty snapshot from which sandbox can be wiped away and re-bootstrapped atop is really all that is needed.

**Comment by jhujasonw** [comment]
The job referenced in https://github.com/jhu-idc/idcApp-k8s/issues/68 is a singular reset that happens when that job is run on the namespace.   For a fully automated reset, this job should be turned into a kubernetes Cron resource and set to run every 14 days.  We would need to agree on a start date for this, and we can set the Cron to start then.   Leaving this open until we decide on a start time for the sandbox resets.

**Comment by birkland** [comment]
For now, will just re-set it on on demand via a low-priority jira ticket.
