### ISSUE TITLE
Architect and Deploy a Kubernetes Cluster in Cloud Provider

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#85]
After we have determined the cloud hosting provider, we will need to configure, build and deploy a Kubernetes cluster. 

Expected outcome:
- [ ] We will have an initially sized cluster, some Kubernetes nodes and administrative level access
- [ ] We will have a namespace created for each of the initially determined environments

**Comment by htpvu** [comment]
@jhujasonw 

The envs we will have are:
Sandbox, test, stage, production

Let me know if this is NOT what you needed.

**Comment by jhujasonw** [comment]
@htpvu  This is done in the https://github.com/jhu-sheridan-libraries/idc-kubernetes repo with PR https://github.com/jhu-sheridan-libraries/idc-kubernetes/pull/10
