### ISSUE TITLE
Propose a alternative spreadsheet format for batch ingest

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#88]
Given the batch ingest spreadsheet format put forth by Elliot, please propose an alternative spreadsheet format (layout/column names) that addresses the usability concern.Alternative spreadsheet format should be user centric and technically accessible to non developing/script writing users.

**Comment by bseeger** [comment]
Here is the alternate setup I'm proposing: https://docs.google.com/document/d/1__fwwYyaXAxiNgmHWsMBmwq9g6cR4wmcOshjNfnf_Bw/edit

**Comment by htpvu** [comment]
Done - reviewed by MD group, Katie and Elliot.
