### ISSUE TITLE
Verify that Islandora CAN generate low resolution images from hi-res ones

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#89]
to support requirements for iDC-15, please verify that the system can indeed generate lo-res derivative from hi-res images. 

if it cannot, we'll have to specify alternative approach in the case of handling hi-res image.

**Comment by bseeger** [comment]
Islandora asset files are marked (by admin) as Original Files when they are uploaded.   There are other choices for marking the file with, but this will be the main one used to indicate what the originally uploaded file was.

Islandora then generates a Service File and Thumbnail file from that Original File to use in various spots in the UI.

tasks:  
- [x] see what size Service Files are after they are generated from Original files.  Is there a decrease in resolution/quality?
Notes: Service Files' mime type ends up being image/jpg 

- [x] see what size and resolution for Thumbnail (just useful to know)
Notes: 100px x 100px, mimetype: image/jpeg

- [x] setup action to generate a smaller image (smaller then Service File, but larger then Thumbnail) to see how easily one can do this in Islandora.  (this will clearly show what control of images we have in Islandora).

**Comment by bseeger** [comment]
I've tried out a few things, as described above.  

### Short answer:  
All in all, Islandora can create low-resolution images from files submitted by admins.  It will need specific attention from us to configure it and ensure that it's setup correctly. 

### Longer Answer: 

Original File = original file uploaded by user
Service File = file derivative of Original File -- this derivative simply changes format from `jpg`, `png`, `gif` to `jpg`. 

Islandora uses ImageMagick to convert the files.  It is part of the [Houdini microservice](https://github.com/Islandora/Crayfish/tree/dev/Houdini) provided by Islandora.  It has two endpoints for ImageMagick commands: one for `identify` and one for `convert`. 

Right now when a file is uploaded and marked as an Original File, a Service file is created for it - It is essentially taking the Original file and making a jpeg from it - even if it is already a jpeg file.   It uses the `convert` command with no conversion parameters.  While it doesn't change size or resolution explicitly, I have observed that the file size sometimes changes a little in the process, so it must change something a little.  Not sure what or why. 

In Islandora this is done via an [Action](http://i8p.cloud.library.jhu.edu:8000/admin/config/system/actions/configure/image_generate_a_service_file_from_an_original_file?destination=/admin/config/system/actions) that is triggered via a [Context](http://i8p.cloud.library.jhu.edu:8000/admin/structure/context/image_original_file).  When a new Media is created, this Context will cause the Action to run, thereby creating the derivative. 

This Context is triggered based on what type of Islandora Media Use this file is marked as (Original File, Service File, etc).  Islandora Media Use is a taxonomy that we can add to and create different reactions for each term in it. 

We can create new Contexts and Actions for different derivatives, should we want to create images of varying resolution. If we want to decrease the resolution on an image, we can put that into the Action's command that is sent to Houdini, as we can control what parameters are sent into the Houdini microservice. 

The hard part is dealing with images of varying resolutions that might be submitted _to_ islandora by the admin user. We can decrease PPI, but if the incoming files vary in resolution, this might not work across the board.  We could just send `convert`  the parameters `-resample 72` (72 PPI) and hope that works for most images (which it probably will). 

All in all, Islandora can create low-resolution images from files submitted by admins.  It will need specific attention from us to configure it and ensure that it's setup correctly.

**Comment by htpvu** [comment]
thanks @bseeger i'll close it.
