### ISSUE TITLE
capturing hi-res and restricted-access characteristics of resources in Drupal model

### ISSUE THREAD

**Issue by htpvu** [jhu-idc/iDC-general#90]
To support use case iDC-15, images needs to have hi-res and restricted-access attributes express as its metadata, please specify where these metadata fields should resides on a drupal model so they can be inspected and acted upon at the time of rendering.

**Comment by bseeger** [comment]
## First part - where to indicate if a media is restricted or high resolution
We would need to put these fields on the Media object, as that is where the file itself is accessed through.  We will have multiple media/files per repository item and most Media will have no restrictions on them.  

We can add "High Resolution File" and "Restricted File" to Islandora Media Use Taxonomy. These would then show up as options on the Media for any file (along with the other existing options like "Original File", "Service File", etc).

The work flow would be that a CA creates a Node (Repository Item), then creates Media for the node. When creating Media, they can use these options to indicate what the image/item is. 

### Ingest
A user can set these fields when creating an Ingest, thereby marking a file high resolution and/or restricted. 

## Second part -- how to stop direct access to media/files
There is a larger question that will affect how the files are accessed/protected.  Drupal generally allows direct access to [media](http://i8p.cloud.library.jhu.edu:8000/media/469) and [files](http://i8p.cloud.library.jhu.edu:8000/_flysystem/fedora/2020-06/a_title_page.jpg) (links are examples from pilot).  Meaning that each file has a URL that is a direct link to the Media or the File.   There are a few things we can do to prevent this and should have a conversation about this once the backend storage plan is firmed up.   (via configuration, the "private:" filesystem setup Drupal allows, or some server tricks like .htaccess files).

In Drupal we can configure it to not allow direct access to Media.  I'm not sure if you can do this for Files. It's probably okay for most things to have a direct link - except the high-res one. So the second part of restricting these images is ensuring that there is no direct link to the image.  

## Summary
So the larger question that will effect how we implement this is whether or not **all** files will be restricted, in general?  For example, will all our files be private (either on S3 or on filesystem)  or _should_ any digital asset files be publicly accessible via a direct link (outside of the Repository Item's page)?    
-  if they will all be private and no direct links are available for anything, then protecting assets from direct access is solved. 
- then it's just a matter of the UI code having a way to tell if it should freely share the hi-res image or not (when requested) and that can be done via the taxonomy values of High-Resolution File and Restricted File (as described above).  The UI can behave in one of two ways: 
   - if high-res image is available for an item and it's not restricted: it can have a link available to down load the image
   - if high-res image is available and restricted, then the UI should show a "request high resolution image" link.

**Comment by bseeger** [comment]
@htpvu I think this is complete. Would you like to see anything added or thought through some more?    Once backend storage is figured out, we should talk about if all images are directly publicly accessible via a URL or not (versus only being accessed via the Repository Item page).

**Comment by htpvu** [comment]
sounds like a good plan. i'll close it.
