### ISSUE TITLE
Set up foundation for ingest UI

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#95]
cceptance criteria:
 
-   	Install UI library
-   	Create a Drupal page to be used for housing the Ingest UI
-   	Ensure this page is linked to from the Admin UI
-   	Ensure JavaScript application can be injected into Drupal page
 
Since most of the work to set up the UI development environment will already have been done as part of the Foundational task for the public facing UI tasks, there may not be a lot of Drupal setup work here. This task will primarily focus on creating the Drupal page and installing the UI library that is decided upon.

**Comment by jaredgalanis** [comment]
- [ ] setup drupal page (1d)
- [ ] other setup not completed in public facing pages (1d)

**Comment by htpvu** [comment]
Deprecated. we're going with a different approach for ingest.
