### ISSUE TITLE
 Implement page to facilitate the viewing of the list of ingests

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#98]
Acceptance criteria

- [ ]  	An admin can visit the Ingest UI and view a list of ingests they have initiated (or all ingests?)
- [ ]   	The list view will provide a date of creation of the ingests
- [ ]            The list view will provide the username of the person who initiated the ingest.
- [ ]   	The list view will provide a status of the ingests (running, finished, etc), perhaps via GET/state/{session-id}
- [ ]  	The list view can be sorted and filtered
- [ ]  	For ingests that are in the pending-approval correct state (processed), the owner of the ingest an admin can approve or discard an ingest from the list view
- [ ] 	Clicking a particular ingest will take a user to a detail view for that ingest

It is probably workable to have the list of ingests and tooling to initiate an ingest present on the same page, they’ll likely just be separate components that co-exist on the same page.

**Comment by jaredgalanis** [comment]
- [ ] implement template and css (2d)
- [ ] sorting / filtering (2d)

**Comment by htpvu** [comment]
Deprecated. we're going with a different approach for ingest.
