### ISSUE TITLE
Implement Detail view of ingest status/information

### ISSUE THREAD

**Issue by cyork** [jhu-idc/iDC-general#99]
Acceptance criteria

- [ ]   	An admin can visit the detail view of an ingest that provides all available top-level information about an ingest (date created, status(es), etc).
- [ ]   	An admin can also see a list/table containing the events emitted by the ingest service while processing the ingest resources
- [ ]   	The event list view can be sorted and filtered
- [ ]   	The event list view can be refreshed manually (with a button)
- [ ]   	For ingests that are in the pending-approval state correct state (processed), the owner of the ingest an admin can approve or discard an ingest from the detail view

Logs of events should probably be updated automatically as they come in. This may not be an actual real-time experience, but the UI should poll the events endpoint or find some strategy for refreshing the data.

**Comment by jaredgalanis** [comment]
- [ ] templating and css (2d)
- [ ] event list table/sorting (2d)

**Comment by htpvu** [comment]
Deprecated. we're going with a different approach for ingest.
